/* ChessSRS live demo — authentic port of Flutter ReviewScreen ("Diagram" identity).
   Board on the left with outer/inner coordinates, fixed regions on the right:
   Meta (Game 1, White to play), Notation Line with dashed blank, Answer/Note Slot, and Skip/Continue actions.
*/
(() => {
  const host = document.getElementById("app"); if (!host) return;
  const { F, START, sq, nm, genB, compile, parsePGN, toPGN, nextInterval } = window.SRSEngine;
  const NS = "http://www.w3.org/2000/svg", $ = (s, c = host) => c.querySelector(s);
  const esc = s => String(s).replace(/[&<>\"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  const days = n => n === 1 ? "1 day" : n + " days";

  /** SAN for every ply of a line, via the same chess.js the page loads. */
  const sanOf = sanStr => {
    const toks = sanStr.split(/\s+/).filter(Boolean);
    const Chess = window.Chess;
    if (!Chess) return toks;                       // no rules engine: show the raw tokens
    const ch = new Chess(), out = [];
    for (const t of toks) {
      const mv = ch.move(t);
      if (!mv) break;
      out.push(mv.san);
    }
    return out;
  };

  /* ---------- study data ----------
     Chapter titles are "Game 1", "Game 2" and so on because that is what the app's importer
     produces: pgn_importer.dart falls back to `Game ${index + 1}` for any game in a PGN with no
     real chapter title, and the review screen's meta row shows `chapterTitle ?? studyTitle`.
     Descriptive chapter names invented here would be the one thing on screen the app itself can
     never produce from a PGN. */
  const PRESETS = [
    {
      name: "Queen Pawn Repertoire",
      side: "w",
      lines: [
        {
          t: "Game 1",
          s: "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 c4 Nbd2",
          note: "The French Defense: Advance Variation",
          noteSource: "From your study"
        },
        {
          t: "Game 2",
          s: "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Bd7 Be2 Nge7 Na3 cxd4 cxd4 Nf5 Nc2",
          note: "Solidity in the center with Bd7 and Be2",
          noteSource: "From your study"
        }
      ]
    },
    {
      name: "Sicilian Defense Repertoire",
      side: "b",
      lines: [
        {
          t: "Game 1",
          s: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6",
          note: "English Attack setup",
          noteSource: "From your study"
        }
      ]
    }
  ];

  const SAMPLE = `[Event "My Rep for White"]\n\n1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. c3 Nf6 5. d4 exd4 6. cxd4 Bb4+ 7. Nc3 Nxe4 8. O-O Bxc3 9. d5 Bf6 10. Re1 Ne7 *`;
  /* Accent list, fonts and motion timings all come from the app repo via assets/app-meta.js
     (generated by scripts/sync-design.js). Nothing here is written down twice: a new accent or
     a retuned duration in the app arrives here on the next sync. */
  const META = window.CHESSSRS_META || { accents: [], motion: {} };
  const ACC = META.accents;
  const MOTION = META.motion || {};
  const QUICK_ADVANCE_MS = MOTION.quietAdvanceMs ?? 560;
  const OPPONENT_REPLY_MS = MOTION.pieceMoveMs ?? 170;
  const set = { theme: "dark", accent: (ACC.find(a => a.default) || ACC[0] || {}).id, sound: false, coords: true, arrows: true, retention: 88, limit: 20, scheduler: "fsrs", showHistory: false, showArrows: true, showNotes: true, diagnostics: false, soundTheme: "Classic", masterVolume: 1 };
  let studies = [], uid = 0, sel = 0, practice = false, queue = [], cur = null, an = null, isrc = "file", sa = 0;

  const mkStudy = (name, side, lines) => {
    const s = { id: ++uid, name, side, active: true, lines: [] };
    for (const l of lines) {
      const m = compile(l.s), line = { t: l.t, s: l.s, note: l.note, noteSource: l.noteSource, m, san: sanOf(l.s), cards: [] };
      m.forEach((_, k) => {
        if ((k % 2 === 0) === (side === "w")) {
          line.cards.push({ k, line, due: true, ivl: 0, lapses: 0 });
        }
      });
      s.lines.push(line);
    }
    return s;
  };

  studies = PRESETS.map(p => mkStudy(p.name, p.side, p.lines));
  /* `sel` is the scope: -1 is the everywhere scope, which is where the app starts and what its
     top bar calls "All repertoires"; >= 0 is one repertoire. `scope()` is the list a session
     draws from, so the review loop never has to care which scope is active. */
  const st = () => (sel >= 0 ? studies[sel] : null);
  const scope = () => (sel >= 0 ? [studies[sel]] : studies);
  const dueN = s => s ? s.lines.reduce((n, l) => n + l.cards.filter(c => c.due).length, 0) : 0;
  const scopeDue = () => scope().reduce((n, s) => n + (s.active ? dueN(s) : 0), 0);
  const SCOPE_ALL = "All repertoires";
  /* The study a Study Actions sheet is acting on: the one it was opened for, falling back to
     the current scope. Actions in the app hang off a repertoire row, not off the session. */
  const tgt = () => studies[sa] || st() || studies[0];

  /* ---------- SVG Icons ---------- */
  const ico = {
    chev: '<path d="m6 9 6 6 6-6"/>',
    dots: '<circle cx="5" cy="12" r="1.8" fill="currentColor"/><circle cx="12" cy="12" r="1.8" fill="currentColor"/><circle cx="19" cy="12" r="1.8" fill="currentColor"/>',
    check: '<path d="m5 12.5 5 5 9-10"/>',
    x: '<path d="M6 6l12 12M18 6 6 18"/>'
  };
  const I = k => `<svg class="ico" viewBox="0 0 24 24" aria-hidden="true">${ico[k]}</svg>`;

  const squares = [...Array(64)].map((_, i) => {
    const f = i & 7, r = i >> 3;
    const isDark = (f + r) % 2 === 1;
    return `<rect x="${f}" y="${r}" width="1" height="1" class="${isDark ? 'sq-d' : 'sq-l'}"/>` +
      (isDark ? `<rect x="${f}" y="${r}" width="1" height="1" fill="url(#hatch)"/>` : '');
  }).join("");

  /* ---------- Shell HTML (Exact review layout mirroring App) ---------- */
  host.innerHTML = `
  <div class="srs-topbar">
    <div class="srs-scope-cluster">
      <button class="srs-scope-btn" data-a="picker" aria-haspopup="dialog" aria-label="Studies and scope">
        <span id="a-study">All repertoires</span>
        <svg class="srs-chev" viewBox="0 0 12 12" aria-hidden="true"><path d="M2.5 4.5L6 8L9.5 4.5" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>
      </button>
      <span class="srs-due-badge" id="a-due">16 due</span>
    </div>
    <div class="srs-topbar-spacer"></div>
    <button class="srs-dots-btn" data-a="more" aria-label="Library and settings">
      <svg class="ico" viewBox="0 0 24 24" aria-hidden="true">${ico.dots}</svg>
    </button>
  </div>

  <div class="srs-review-main ab">
    <div class="srs-board-region">
      <div class="srs-board-wrap bw">
        <div class="rk" aria-hidden="true"></div>
        <svg class="bd" viewBox="0 0 8 8" role="application" tabindex="0" aria-label="Chess board. Arrow keys move the cursor, Enter picks up or drops a piece.">
          <defs>
            <pattern id="hatch" width=".1" height=".1" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">
              <rect width=".012" height=".1" fill="currentColor"/>
            </pattern>
            ${window.PIECE_DEFS}
          </defs>
          <g class="board-squares">${squares}</g>
          <g class="ov"></g>
          <g class="pcs"></g>
          <g class="arr" style="color:var(--aa)" opacity=".95"></g>
          <rect x="0.02" y="0.02" width="7.96" height="7.96" fill="none" stroke="currentColor" stroke-width="1.5" vector-effect="non-scaling-stroke" class="board-frame"/>
        </svg>
        <div class="fl" aria-hidden="true"></div>
      </div>
    </div>

    <div class="srs-side-column ap">
      <div id="a-rev" class="srs-rev-pane">
        <div class="srs-meta">
          <span class="srs-chapter-name at" id="a-title"></span>
          <div class="srs-turn-indicator aw">
            <span class="srs-turn-dot tn"></span>
            <span id="a-turn">White to play</span>
          </div>
        </div>

        <div class="srs-notation-line" id="a-notation-line"></div>

        <div class="srs-slot-region" id="a-slot-region">
          <div class="srs-note-slot" id="a-note" hidden>
            <p class="srs-note-body" id="a-note-body"></p>
            <span class="srs-note-source" id="a-note-source">From your study</span>
          </div>
          <div class="srs-correction-slot rv" id="a-rv" hidden>
            <svg class="pi" viewBox="0 0 100 100" aria-hidden="true" width="56" height="56"></svg>
            <span class="srs-corr-san" id="a-sq">d4</span>
            <p class="srs-corr-help">Play this move to continue. The position will come back soon.</p>
          </div>
        </div>

        <div class="srs-actions-region act" id="a-act">
          <button class="srs-skip-btn sk" data-a="skip" id="a-skip">Skip <kbd>S</kbd></button>
          <button class="srs-cont-btn pill" data-a="cont" id="a-cont" hidden>Continue <kbd>Space</kbd></button>
        </div>
      </div>

      <div id="a-an" class="srs-rev-pane" hidden></div>
      <div id="a-empty" class="srs-rev-pane" hidden></div>
    </div>
  </div>

  <div class="mo" id="a-mo" hidden></div>
  <p class="sr" role="status" aria-live="polite" id="a-live"></p>`;

  /* ---------- Board Engine & Interaction ---------- */
  const bd = $(".bd"), layer = $(".pcs"), ov = $(".ov"), arr = $(".arr"), mo = $("#a-mo");
  let flip = false, pcs = [], selSq = -1, dests = [], drag = null, enabled = false, timer = 0, user = "w", lastMove = null, ac = null, opener = null, kb = -1, kbOn = false;
  const kc = { c: 4, r: 6 }, PN = { k: "king", q: "queen", r: "rook", b: "bishop", n: "knight", p: "pawn" };
  const at = i => pcs.find(p => p.i === i), D = i => [flip ? 7 - (i & 7) : i & 7, flip ? 7 - (i >> 3) : i >> 3];

  /* Piece geometry comes from pieces.js, generated from the app's own SVGs. The app draws a
     piece in its own viewBox coordinates ("5 2 90 90"), so fitting it to a square means scaling
     by the inverse of that box's size and cancelling its origin. Both are derived from the
     exported viewBox rather than written down here: if the app re-cuts the artwork, this
     follows instead of drawing pieces off the board. */
  const PV = (window.PIECE_VIEWBOX || "0 0 100 100").trim().split(/\s+/).map(Number);
  const [pvX, pvY, pvW] = PV;
  const PC_S = 1 / (PV[2] || 100);
  const PC_T = `scale(${PC_S}) translate(${-pvX} ${-pvY})`;

  /* Three layers, matching the app: halo, line, fill. Colour comes from CSS custom properties
     (--halo, --ws/--wf for white, --bs/--bf for black) so a theme or accent change in the app
     repaints the pieces with no change here. */
  const art = ch => {
    const t = ch.toUpperCase(), isWhite = ch < "a";
    return `<g class="pc-g ${isWhite ? "w" : "b"}" transform="${PC_T}">` +
      `<use href="#pc-${t}" class="halo"/><use href="#pc-${t}" class="line"/><use href="#pc-${t}" class="fill"/></g>`;
  };

  const place = (p, i) => { p.i = i; const [c, r] = D(i); p.el.style.transform = `translate(${c}px,${r}px)`; };
  const labels = () => {
    $(".rk").innerHTML = [...Array(8)].map((_, r) => `<span>${flip ? r + 1 : 8 - r}</span>`).join("");
    $(".fl").innerHTML = [...Array(8)].map((_, c) => `<span>${F[flip ? 7 - c : c]}</span>`).join("");
  };

  function ping() {
    if (!set.sound) return;
    try {
      ac = ac || new (window.AudioContext || window.webkitAudioContext)();
      const o = ac.createOscillator(), g = ac.createGain();
      o.frequency.value = 620; g.gain.value = .04;
      o.connect(g); g.connect(ac.destination);
      o.start(); o.stop(ac.currentTime + .05);
    } catch (e) {}
  }

  function setup(fen, f) {
    layer.innerHTML = ""; pcs = []; flip = f; labels(); selSq = -1; dests = []; mark(); arrow();
    fen.split("/").forEach((row, r) => {
      let c = 0;
      for (const ch of row) {
        if (+ch) { c += +ch; continue; }
        const el = document.createElementNS(NS, "g");
        el.setAttribute("class", "p " + (ch < "a" ? "w" : "b"));
        el.innerHTML = art(ch);
        layer.append(el);
        const p = { ch, el, i: 0 };
        place(p, r * 8 + c);
        pcs.push(p);
        c++;
      }
    });
  }

  function move(f, t) {
    const p = at(f), c = at(t), k = p.ch.toLowerCase(), drop = x => { if (x) { x.el.remove(); pcs.splice(pcs.indexOf(x), 1); } };
    drop(c);
    if (k === "p" && (f & 7) !== (t & 7) && !c) drop(at((f >> 3) * 8 + (t & 7)));
    if (k === "k" && Math.abs((f & 7) - (t & 7)) === 2) {
      const r = at((f >> 3) * 8 + (t > f ? 7 : 0));
      r && place(r, (f >> 3) * 8 + (t > f ? 5 : 3));
    }
    if (k === "p" && (t >> 3 === 0 || t >> 3 === 7)) {
      p.ch = p.ch < "a" ? "Q" : "q";
      p.el.innerHTML = art(p.ch);
    }
    place(p, t);
  }

  const gen = i => {
    const b = Array(64).fill("");
    pcs.forEach(p => b[p.i] = p.ch);
    return genB(b, i);
  };

  function mark(last, selected) {
    const box = (i, o) => {
      const [c, r] = D(i);
      return `<rect x="${c}" y="${r}" width="1" height="1" style="fill:var(--aa)" opacity="${o}"/>`;
    };
    let h = (last || []).map(i => box(i, .35)).join("") + (selected >= 0 ? box(selected, .55) : "");
    dests.forEach(i => {
      const [c, r] = D(i);
      h += at(i)
        ? `<circle cx="${c + .5}" cy="${r + .5}" r=".43" fill="none" stroke="#0D0F13" stroke-opacity=".45" stroke-width=".08"/>`
        : `<circle cx="${c + .5}" cy="${r + .5}" r=".15" fill="#0D0F13" fill-opacity=".45"/>`;
    });
    if (kbOn && kb >= 0) {
      const [c, r] = D(kb);
      h += `<rect x="${c + .04}" y="${r + .04}" width=".92" height=".92" fill="none" style="stroke:var(--aa)" stroke-width=".07"/>`;
    }
    ov.innerHTML = h;
  }

  function arrow(m) {
    arr.innerHTML = "";
    if (!m || !set.arrows) return;
    const P = i => D(i).map(v => v + .5), [x1, y1] = P(sq(m.slice(0, 2))), [x2, y2] = P(sq(m.slice(2, 4))), dx = x2 - x1, dy = y2 - y1;
    const cx = (x1 + x2) / 2 - dy * .14, cy = (y1 + y2) / 2 + dx * .14, ux = x2 - cx, uy = y2 - cy, l = Math.hypot(ux, uy), hx = ux / l, hy = uy / l, h = .44;
    arr.innerHTML = `<path d="M${x1} ${y1}Q${cx} ${cy} ${x2 - hx * h * .8} ${y2 - hy * h * .8}" fill="none" stroke="currentColor" stroke-width=".17" stroke-linecap="round"/>` +
      `<path d="M${x2} ${y2}L${x2 - hx * h - hy * .25} ${y2 - hy * h + hx * .25}L${x2 - hx * h + hy * .25} ${y2 - hy * h - hx * .25}Z" fill="currentColor"/>`;
  }

  const snapTo = (L, n, side) => {
    layer.classList.add("snap"); setup(START, side === "b");
    for (let j = 0; j < n; j++) move(sq(L.m[j].slice(0, 2)), sq(L.m[j].slice(2, 4)));
    lastMove = n ? [sq(L.m[n - 1].slice(0, 2)), sq(L.m[n - 1].slice(2, 4))] : null;
    mark(lastMove, -1);
    setTimeout(() => layer.classList.remove("snap"), 40);
  };

  /* ---------- Pointer Input ---------- */
  const idx = e => {
    const r = bd.getBoundingClientRect(), cl = v => Math.min(7, Math.max(0, v)),
      c = cl(Math.floor((e.clientX - r.left) / r.width * 8)), w = cl(Math.floor((e.clientY - r.top) / r.height * 8));
    return flip ? (7 - w) * 8 + 7 - c : w * 8 + c;
  };
  const mine = p => (p.ch < "a") === (user === "w");
  const select = i => { selSq = i; dests = i < 0 ? [] : gen(i); mark(lastMove, i); };

  bd.addEventListener("pointerdown", e => {
    if (!enabled) return;
    const i = idx(e), p = at(i);
    if (selSq >= 0 && dests.includes(i)) return attempt(selSq, i);
    if (p && mine(p)) {
      select(i);
      drag = { p, from: i, x: e.clientX, y: e.clientY, moved: false };
      p.el.style.transition = "none";
      layer.append(p.el);
      bd.setPointerCapture(e.pointerId);
    } else {
      select(-1);
    }
  });

  bd.addEventListener("pointermove", e => {
    if (!drag) return;
    if (Math.hypot(e.clientX - drag.x, e.clientY - drag.y) > 5) drag.moved = true;
    if (drag.moved) {
      const r = bd.getBoundingClientRect(), s = r.width / 8;
      drag.p.el.style.transform = `translate(${(e.clientX - r.left) / s - .5}px,${(e.clientY - r.top) / s - .5}px)`;
    }
  });

  const release = (e, cancel) => {
    if (!drag) return;
    const { p, from, moved } = drag;
    drag = null;
    p.el.style.transition = "";
    const i = cancel ? -1 : idx(e);
    if (moved && dests.includes(i)) attempt(from, i);
    else { place(p, from); if (moved) select(-1); }
  };
  bd.addEventListener("pointerup", e => release(e));
  bd.addEventListener("pointercancel", e => release(e, true));

  /* ---------- Keyboard Input ---------- */
  const NAMES = { k: "king", q: "queen", r: "rook", b: "bishop", n: "knight", p: "pawn" };
  const desc = i => {
    const p = at(i);
    return nm(i) + (p ? `, ${p.ch < "a" ? "white" : "black"} ${NAMES[p.ch.toLowerCase()]}` : ", empty");
  };

  bd.addEventListener("focus", () => {
    kbOn = true;
    if (kb < 0) kb = sq(user === "w" ? "e2" : "e7");
    mark(lastMove, selSq);
    say(desc(kb));
  });
  bd.addEventListener("blur", () => { kbOn = false; mark(lastMove, selSq); });
  bd.addEventListener("keydown", e => {
    const arrows = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, -1], ArrowDown: [0, 1] };
    if (arrows[e.key]) {
      e.preventDefault();
      const [c, r] = D(kb), nc = Math.min(7, Math.max(0, c + arrows[e.key][0])), nr = Math.min(7, Math.max(0, r + arrows[e.key][1]));
      kb = flip ? (7 - nr) * 8 + 7 - nc : nr * 8 + nc;
      mark(lastMove, selSq);
      say(desc(kb));
      return;
    }
    if (e.key === "Escape") { select(-1); say("Selection cleared"); return; }
    if (e.key !== "Enter" && e.key !== " ") return;
    e.preventDefault();
    if (!enabled) return;
    const p = at(kb);
    if (selSq >= 0 && dests.includes(kb)) return attempt(selSq, kb);
    if (p && mine(p)) {
      select(kb);
      say(`${desc(kb)} selected. ${dests.length} squares to move to.`);
    } else {
      select(-1);
      say(`${desc(kb)}. Not one of your pieces.`);
    }
  });

  /* ---------- Review Session Engine ---------- */
  const say = t => $("#a-live").textContent = t;
  const view = n => {
    $("#a-rev").hidden = n !== "rev";
    $("#a-an").hidden = n !== "an";
    $("#a-empty").hidden = n !== "empty";
  };

  function head() {
    const s = st();
    const live = scope().filter(x => x.active);
    $("#a-study").textContent = !s ? (studies.length ? SCOPE_ALL : "No repertoire") : s.name;
    $("#a-due").textContent = !studies.length ? ""
      : !live.length ? "Paused"
      : practice ? "Practice"
      : (sel >= 0 ? dueN(s) : scopeDue()) + " due";
  }

  const turn = () => {
    const isW = user === "w";
    $("#a-turn").textContent = (isW ? "White" : "Black") + " to play" + (practice ? " · Practice" : "");
    const dot = $(".srs-turn-dot");
    if (dot) dot.style.background = isW ? "transparent" : "var(--ink)";
  };

  function startSession() {
    clearTimeout(timer); cur = null; an = null; enabled = false;
    queue = [];
    // Cards carry their own study, so a session can span the everywhere scope and still know
    // which side to sit on for each position.
    for (const s of scope()) {
      if (!s.active) continue;
      for (const c of s.lines.flatMap(l => l.cards)) c.s = s;
    }
    const all = scope().filter(s => s.active).flatMap(s => s.lines.flatMap(l => l.cards));
    queue = (practice ? all : all.filter(c => c.due)).slice(0, set.limit);
    head();
    queue.length ? present(queue[0]) : empty();
  }

  function present(c) {
    clearTimeout(timer);
    const s = c.s || st(), L = c.line, again = cur && cur.line === L && c.k === cur.k + 2;
    view("rev");
    user = s.side;
    enabled = false;
    $("#a-title").textContent = L.t;
    // Open on the decision slot: every ply up to here is history, and this one is the question.
    $("#a-notation-line").innerHTML = notationHTML(L.san.slice(0, c.k), null);
    $("#a-note").hidden = true;
    $("#a-rv").hidden = true;
    $("#a-cont").hidden = true;
    $("#a-skip").hidden = false;
    arrow();
    head();

    const go = () => { cur = { c, line: L, missed: false, wait: false }; enabled = true; turn(); };
    if (again) {
      play(L.m[cur.c.k + 1]);
      timer = setTimeout(go, OPPONENT_REPLY_MS * 2 + 90);
    } else {
      snapTo(L, c.k, s.side);
      go();
    }
  }

  function play(m) {
    const f = sq(m.slice(0, 2)), t = sq(m.slice(2, 4));
    move(f, t);
    lastMove = [f, t];
    mark(lastMove, -1);
    ping();
  }

  /* The answer slot below the notation line — the app's _AnswerSlot: the expected move in SAN
     with a figurine for pieces, then "Play this move to continue. The position will come back
     soon." A coordinate is not shown anywhere in the app. */
  const revealSan = () => {
    const k = cur ? cur.c.k : -1;
    return k >= 0 && cur.line.san[k] ? cur.line.san[k] : "";
  };

  function reveal(m) {
    if (!m) {
      arrow();
      $("#a-rv").hidden = true;
      return;
    }
    arrow(m);
    const sanText = revealSan() || m.slice(2, 4);
    $("#a-sq").innerHTML = sanFig(sanText);
    $("#a-rv").hidden = false;
    say(`Play ${sanText} to continue.`);
  }

  function rate(c, ok) {
    if (practice) return;
    if (ok) {
      c.ivl = nextInterval(c.ivl, set.retention);
      c.due = false;
    } else {
      c.lapses++;
      c.ivl = 0;
      c.due = true;
    }
    head();
  }

  function miss() {
    if (!cur.missed) {
      cur.missed = true;
      rate(cur.c, false);
    }
  }

  /* ---------- Notation ----------
     Mirrors SrsNotationLine: completed move *pairs* (so a number never wraps away from its
     move), the line truncated to the last 8 plies behind a leading ellipsis, and the decision
     slot drawn as either the dashed blank or the answer in the accent. A leading piece letter is
     swapped for its figurine, as SrsSan does. */
  const FIG = window.FIGURINES || {};

  const sanFig = san => {
    if (!san) return "";
    const f = FIG[san[0]];
    if (!f) return esc(san);
    return `<svg class="srs-fig" viewBox="${f.vb}" aria-hidden="true">${f.body}</svg>${esc(san.slice(1))}`;
  };

  /**
   * @param history  SAN of every ply before the decision
   * @param answer   SAN to show in the slot, or null to show the dashed blank
   */
  function notationHTML(history, answer) {
    let startPly = 0, visible = history;
    if (history.length > 8) {
      // Start on an even ply so the line opens on a move number rather than mid-pair, which is
      // what the leading ellipsis is there to explain.
      const excess = history.length - 8;
      startPly = excess % 2 === 0 ? excess : excess - 1;
      visible = history.slice(startPly);
    }
    const n = visible.length;
    const blackToMove = n % 2 === 1;
    const completed = blackToMove ? n - 1 : n;
    const slot = answer
      ? `<span class="srs-move-san">${sanFig(answer)}</span>`
      : `<span class="srs-dashed-blank"></span>`;

    let h = startPly > 0 ? `<span class="srs-move-num">…</span>` : "";
    for (let i = 0; i < completed; i += 2) {
      const num = Math.floor((startPly + i) / 2) + 1;
      h += `<span class="srs-pair"><span class="srs-move-num">${num}.</span>${sanFig(visible[i])}` +
        (i + 1 < n ? `<span class="srs-gap"></span>${sanFig(visible[i + 1])}` : "") + `</span>`;
    }
    const decisionNumber = Math.floor((startPly + n) / 2) + 1;
    const head = `<span class="srs-move-num" id="a-move-num">${decisionNumber}.</span>`;
    h += blackToMove
      ? `<span class="srs-pair">${head}${sanFig(visible[n - 1])}<span class="srs-gap"></span>${slot}</span>`
      : `<span class="srs-pair">${head}${slot}</span>`;
    return h;
  }

  function attempt(f, t) {
    select(-1);
    const want = cur.line.m[cur.c.k];
    if (nm(f) + nm(t) === want.slice(0, 4)) {
      move(f, t);
      lastMove = [f, t];
      mark(lastMove, -1);
      ping();
      enabled = false;
      reveal();

      // Fill the decision slot. The app reveals `expectedMoves.first.san` — the repertoire
      // move, not whatever was played — so a transposition still shows what the app would.
      const sanMove = cur.line.san[cur.c.k] || want.slice(2, 4);
      $("#a-notation-line").innerHTML = notationHTML(cur.line.san.slice(0, cur.c.k), sanMove);

      // Line-level notes are chapter context, not per-move PGN comments:
      // per the Flutter app (_hasAnnotationsOrShapes on the prompt comment),
      // they must not pause auto-advancement. Only a lapse waits for Continue.
      // The turn row is left alone here. In the app it only ever reads "White to play" or
      // "Black to play" — the review interval is shown nowhere on screen, and the verdict is
      // carried to screen readers by a visually hidden live region. Overwriting this row with
      // "Remembered · back in 3 days" put text on the app's quiet-by-design surface.
      if (cur.missed) {
        cur.wait = true;
        $("#a-skip").hidden = true;
        $("#a-cont").hidden = false;
        // Lapse + comment in the app shows Answer + Note together.
        if (cur.line.note) {
          $("#a-note-body").textContent = cur.line.note;
          $("#a-note-source").textContent = cur.line.noteSource || "From your study";
          $("#a-note").hidden = false;
        }
        say(`Correct. ${sanMove}.`);
      } else {
        rate(cur.c, true);
        say(`Correct. ${sanMove}.`);
        timer = setTimeout(next, QUICK_ADVANCE_MS);
      }
    } else {
      miss();
      reveal(want);
      if (cur.line.note) {
        $("#a-note-body").textContent = cur.line.note;
        $("#a-note-source").textContent = cur.line.noteSource || "From your study";
        $("#a-note").hidden = false;
      }
      place(at(f), f);
      // The app's wording, verbatim: review_screen.dart's _verdictAnnouncement.
      say(`Not this move. The repertoire move is ${revealSan()}.`);
    }
  }

  const skip = () => {
    if (enabled && cur) {
      miss();
      reveal(cur.line.m[cur.c.k]);
      if (cur.line.note) {
        $("#a-note-body").textContent = cur.line.note;
        $("#a-note-source").textContent = cur.line.noteSource || "From your study";
        $("#a-note").hidden = false;
      }
    }
  };

  const cont = () => {
    if (cur && cur.wait) next();
  };

  function next() {
    const done = queue.shift();
    if (cur.missed && !practice) queue.push(done);
    head();
    queue.length ? present(queue[0]) : empty();
  }

  function empty() {
    enabled = false; cur = null; select(-1); arrow();
    view("empty"); head();
    const s = st();
    const live = scope().filter(x => x.active);
    let h;
    if (!studies.length) {
      h = `<h3>No repertoire yet</h3><p>Import a PGN to start reviewing.</p><button class="pill" data-a="import">Import repertoire</button>`;
    } else if (!live.length) {
      h = `<h3>Paused</h3><p>Reviews for this repertoire are paused.</p><button class="pill" data-a="pause">Resume</button>`;
    } else {
      const iv = live.flatMap(x => x.lines.flatMap(l => l.cards.map(c => c.ivl))).filter(x => x > 0);
      const where = s ? s.name : SCOPE_ALL;
      h = `<h3>All caught up</h3><p>Nothing is due in ${esc(where)}.${iv.length ? " The next review is in " + days(Math.min(...iv)) + "." : " The next review is in a few hours."}</p>` +
        `<div class="cta2"><button class="pill" data-a="practice">Practice</button><button class="sk" data-a="restart">Start over</button></div>`;
    }
    $("#a-empty").innerHTML = h;
  }

  /* ---------- Analyze View ---------- */
  function showPly(i) {
    an.i = Math.max(0, Math.min(an.L.m.length, i));
    snapTo(an.L, an.i, st().side);
    drawAn();
  }

  function drawAn() {
    const t = an.L.s.split(" ");
    $("#a-an").innerHTML = `<p class="srs-chapter-name at">${esc(an.L.t)}</p><div class="mv">${t.map((x, i) => (i % 2 ? "" : `<span class="n">${Math.floor(i / 2) + 1}.</span>`) + `<button data-a="ply" data-i="${i + 1}" class="${an.i === i + 1 ? "on" : ""}">${esc(x)}</button>`).join("")}</div>` +
      `<div class="srs-actions-region act"><button class="srs-skip-btn sk" data-a="aback">Back to review</button><span class="nv2"><button data-a="aprev" aria-label="Previous move">‹</button><button data-a="anext" aria-label="Next move">›</button></span></div>`;
  }

  function analyze() {
    closeModal();
    const s = st();
    clearTimeout(timer);
    const L = cur ? cur.line : s.lines[0];
    cur = null; enabled = false; arrow();
    view("an");
    an = { L, i: 0 };
    showPly(0);
  }

  /* ---------- Modals / Sheets ---------- */
  /* `title` may be null: the app's Library and Study Actions sheets open without a title bar,
     carrying a group header inside the sheet instead (library_sheet.dart, and the `title` column
     of StudyActionsSheet). Only the sheet's own close control stays. */
  function modal(title, body) {
    opener = document.activeElement;
    const head = title === null
      ? `<div class="sht bare"><button class="x" data-a="close" aria-label="Close">${I("x")}</button></div>`
      : `<div class="sht"><b>${esc(title)}</b><button class="x" data-a="close" aria-label="Close">${I("x")}</button></div>`;
    mo.innerHTML = `<div class="sh" role="dialog" aria-modal="true" aria-label="${esc(title || body.replace(/<[^>]+>/g, " ").slice(0, 60))}">${head}${body}</div>`;
    mo.hidden = false;
    (mo.querySelector("[autofocus],textarea,input:not([type=file]),.row,.pill") || mo.querySelector(".x")).focus();
  }

  function closeModal() {
    if (mo.hidden) return;
    mo.hidden = true;
    mo.innerHTML = "";
    opener && opener.focus && opener.focus();
  }

  const row = (a, label, sub, extra = "") => `<button class="row ${extra}" data-a="${a}"><span>${label}${sub ? `<small>${sub}</small>` : ""}</span></button>`;

  /* The scope list: the everywhere row, then one row per repertoire with its due count, its own
     options button, and Import PGN at the foot (review_scope_drawer.dart). */
  const picker = () => modal(null, `<div class="sheet">` +
    `<div class="sheet-group">` +
    `<button class="sheet-row" data-a="scope" data-all="1"><span class="sheet-row-text"><span class="sheet-row-label">All repertoires</span><span class="sheet-row-sub">${studies.reduce((n, s) => n + dueN(s), 0)} due</span></span><svg class="sheet-chevron" viewBox="0 0 14 14" aria-hidden="true"><path d="M3.5 4.5L7 8L10.5 4.5" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button>` +
    studies.map((s, i) => `<div class="sheet-row-wrap"><button class="sheet-row" data-a="pick" data-i="${i}"><span class="sheet-row-text"><span class="sheet-row-label">${esc(s.name)}</span><span class="sheet-row-sub">${s.active ? dueN(s) + " due" : "Paused"}</span></span>${i === sel ? `<svg class="sheet-chevron" viewBox="0 0 14 14" aria-hidden="true"><path d="M3.5 4.5L7 8L10.5 4.5" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>` : ""}</button>` +
      `<button class="sheet-opt" data-a="sacts" data-i="${i}" aria-label="Study options">${I("dots")}</button></div>`).join("") +
    `</div>` +
    `<div class="sheet-group"><button class="sheet-row" data-a="import"><span class="sheet-row-text"><span class="sheet-row-label">Import PGN</span></span></button></div>` +
    `</div>`);

  /* The overflow button opens the Library sheet, which in the app carries two rows under a
     "Preferences" header and nothing else (library_sheet.dart). Study-level actions are not
     here: they live in StudyActionsSheet, reached from a study's options button in the scope
     list — see `studyActions`. */
  const more = () => modal(null, `<div class="sheet">` +
    `<div class="sheet-group"><h4 class="gh" style="padding:14px 20px 4px;margin:0">Preferences</h4>` +
    `<button class="sheet-row" data-a="settings"><span class="sheet-row-text"><span class="sheet-row-label">Settings</span><span class="sheet-row-sub">Review, board, engine, and sound</span></span><svg class="sheet-chevron" viewBox="0 0 14 14" aria-hidden="true"><path d="M3.5 4.5L7 8L10.5 4.5" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button>` +
    `<button class="sheet-row" data-a="about"><span class="sheet-row-text"><span class="sheet-row-label">About and licences</span></span><svg class="sheet-chevron" viewBox="0 0 14 14" aria-hidden="true"><path d="M3.5 4.5L7 8L10.5 4.5" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button>` +
    `</div>` +
    `</div>`);

  /* StudyActionsSheet: three hairline-separated groups, in the app's order and wording.
     No chevrons (app: §12 says "no icons"), hairline separators between groups. */
  function studyActions(i) {
    const s = studies[i];
    if (!s) return;
    sa = i;
    closeModal();
    modal(null, `<div class="sheet">` +
      `<h4 class="gh" style="padding:14px 20px 4px;margin:0">${esc(s.name)}</h4>` +
      `<div class="sheet-group">` +
      `<button class="sheet-row" data-a="analyze"><span class="sheet-row-text"><span class="sheet-row-label">Analyze</span><span class="sheet-row-sub">Browse moves and variations</span></span></button>` +
      `<button class="sheet-row" data-a="practice"><span class="sheet-row-text"><span class="sheet-row-label">${practice ? "End practice" : "Practice"}</span><span class="sheet-row-sub">Drill lines without changing your schedule</span></span></button>` +
      `</div>` +
      `<div class="sheet-group">` +
      `<button class="sheet-row" data-a="export"><span class="sheet-row-text"><span class="sheet-row-label">Export PGN</span><span class="sheet-row-sub">Share or copy standard PGN notation</span></span></button>` +
      `<button class="sheet-row" data-a="pause"><span class="sheet-row-text"><span class="sheet-row-label">${s.active ? "Pause" : "Resume"}</span><span class="sheet-row-sub">${s.active ? "Suspend from active review pool" : "Activate in review pool"}</span></span></button>` +
      `</div>` +
      `<div class="sheet-group">` +
      `<button class="sheet-row" data-a="rename"><span class="sheet-row-text"><span class="sheet-row-label">Rename</span></span></button>` +
      `<button class="sheet-row" data-a="delete"><span class="sheet-row-text"><span class="sheet-row-label">Delete</span></span></button>` +
      `</div>` +
      `</div>`);
  }

  const switchRow = (k, label) => `<label class="row"><span>${label}</span><input type="checkbox" role="switch" data-k="${k}" ${set[k] ? "checked" : ""}></label>`;

  /* Segmented control: single-select pill group. The app's SrsSegmented wraps in a rounded
     container with hairline border; selected pill is ink on ground, others are transparent. */
  const seg = (opts, val, onChange, name) => {
    const b = Object.entries(opts).map(([k, v]) => `<button class="seg-btn${k == val ? " on" : ""}" data-a="${onChange}" data-v="${k}" aria-pressed="${k == val}">${v}</button>`).join("");
    return `<span class="seg" data-n="${name}">${b}</span>`;
  };

  /* Switch: 44x26 toggle with animated thumb. The app's SrsSwitch uses a 44x44 hit area,
     the thumb is 20x20, track is 26px wide. */
  const sw = (k, label) => `<label class="sw"><span>${label}</span><span class="tog${set[k] ? " on" : ""}" data-k="${k}" role="switch" aria-checked="${set[k]}"><i></i></span></label>`;

  /* Accent dots: the app's SrsAccentDots shows circles in a rounded container, selected has an
     ink ring. Values are the accent IDs. */
  const accentDots = () => `<span class="adots">${ACC.map(a => `<button class="adot${a.id === set.accent ? " on" : ""}" data-a="accent" data-v="${a.id}" aria-label="${a.name}" aria-pressed="${a.id === set.accent}" style="--c:${a[set.theme] || a.dark}"></button>`).join("")}</span>`;

  /* Settings row: label + optional help text + trailing control. Below 520px the control stacks
     under the text (app's SrsSettingsRow reflows at 520). */
  const sr = (label, help, control) => `<div class="sr"><div class="sr-text"><b>${label}</b>${help ? `<small>${help}</small>` : ""}</div><div class="sr-trail">${control}</div></div>`;

  /* Navigation row: label + help + value on the right, acts as a button. */
  const nav = (label, help, value, action) => `<button class="sr sr-nav" data-a="${action}"><div class="sr-text"><b>${label}</b>${help ? `<small>${help}</small>` : ""}</div><div class="sr-trail">${esc(value)}</div></button>`;

  const settings = () => modal(null, `<h4 class="gh" style="margin-top:-6px">Settings</h4>` + [
    /* 1. Account — only present if we had auth; in demo we show a placeholder. */
    // `<div class="grp"><h5 class="gh">Account</h5>${sr("Lichess account", "Sign in to import private and unlisted studies.", `<span class="sr-val">Not signed in</span>`)}</div>`,

    /* 2. Review & Spaced Repetition */
    `<div class="grp"><h5 class="gh">Review & Spaced Repetition</h5>` +
    sr("Daily limit", "Positions reviewed per day.",
       seg({25:"25",50:"50",100:"100",150:"150",200:"200",0:"None"}, set.limit, "limit")) +
    sr("Target retention", "Higher means more reviews. 88% suits most players; 95% is for tournament preparation.",
       seg({0.80:"80%",0.85:"85%",0.88:"88%",0.90:"90%",0.95:"95%"}, set.retention, "retention")) +
    sr("Scheduling algorithm", "FSRS adapts to how well you remember each position.",
       seg({fsrs:"FSRS",simple:"Simple",easeScaling:"Ease"}, set.scheduler || "fsrs", "scheduler")) +
    sr("Show move notation", "Display preceding moves (e.g. 1. e4 e5) in the review screen.",
       sw("showHistory", "")) +
    sr("Show arrows and circles", "Drawn from your study, only after you answer.",
       sw("showArrows", "")) +
    sr("Show notes after a move", "Comments from your study appear once you have answered.",
       sw("showNotes", "")) +
    sr("Review Diagnostics HUD", "Show real-time FSRS retrievability, stability, and difficulty HUD in review.",
       sw("diagnostics", "")) +
    `</div>`,

    /* 3. Appearance & Theme */
    `<div class="grp"><h5 class="gh">Appearance & Theme</h5>` +
    sr("Theme", "",
       seg({false:"Light",true:"Dark"}, set.theme === "dark", "theme")) +
    sr("Accent", "Colour of the correct move arrow and selection.", accentDots()) +
    nav("Theme & appearance", "AMOLED, board brightness, and hue.", set.theme === "dark" ? "Dark" : "Light", "themeAdv") +
    `</div>`,

    /* 4. Board & Pieces */
    `<div class="grp"><h5 class="gh">Board & Pieces</h5>` +
    nav("Board & pieces", "Board themes, piece sets, and move coordinates.", "System / Default", "boardAdv") +
    `</div>`,

    /* 5. Sound & Audio */
    `<div class="grp"><h5 class="gh">Sound & Audio</h5>` +
    sr("Sound", "", sw("sound", "")) +
    nav("Sound & audio details", "Sound theme and master volume slider.", `${set.soundTheme || "Classic"} (${Math.round((set.masterVolume||1)*100)}%)`, "soundAdv") +
    `</div>`,

    /* 6. Chess Engine */
    `<div class="grp"><h5 class="gh">Chess Engine</h5>` +
    nav("Chess engine", "Threads, hash memory, search time, and multi-PV lines.", "", "engineAdv") +
    `</div>`,

    /* 7. Data & Diagnostics */
    `<div class="grp"><h5 class="gh">Data & Diagnostics</h5>` +
    sr("Local database size", "Storage used by local database files.", `<span class="sr-val">~0 MB (demo)</span>`) +
    nav("HTTP network logs", "Inspect raw HTTP requests and responses.", "", "httpLogs") +
    nav("App diagnostics logs", "Application error and debug traces.", "", "appLogs") +
    `</div>`,

    /* 8. About */
    `<div class="grp"><h5 class="gh">About</h5>` +
    `<button class="sr sr-nav" data-a="rate"><div class="sr-text"><b>Rate this app</b><small>Open the store listing for Chess Repertoire SRS.</small></div></button>` +
    `<button class="sr sr-nav" data-a="licences"><div class="sr-text"><b>Licences & open source</b><small>GPL-3.0, chessground, dartchess, and third-party notices.</small></div></button>` +
    `</div>`
  ].join(""));

  const about = () => modal("About and licences", `<p class="pad">ChessSRS 0.2.0 is free software under GPL-3.0, a fork of Lichess Mobile. This demo runs entirely in your browser and saves nothing.</p><div class="grp"><a class="row" href="https://github.com/mansourvery-hub/ChessSRS" target="_blank" rel="noopener"><span>ChessSRS source</span></a><a class="row" href="https://github.com/lichess-org/mobile" target="_blank" rel="noopener"><span>Lichess Mobile source</span></a></div>`);

  const importModal = () => {
    isrc = "file";
    modal("Import Repertoire", `<div class="seg wide">${[["lichess", "Lichess Study"], ["file", "PGN Text / File"]].map(([v, l]) => `<button data-a="isrc" data-v="${v}" aria-pressed="${v === "file"}">${l}</button>`).join("")}</div>
    <div id="i-file"><textarea id="i-pgn" rows="6" spellcheck="false" aria-label="PGN text">${esc(SAMPLE)}</textarea><label class="filebtn">Choose a .pgn file<input type="file" id="i-f" accept=".pgn,.txt"></label></div>
    <div id="i-li" hidden><input id="i-url" placeholder="https://lichess.org/study/…" aria-label="Lichess study URL"></div>
    <input id="i-title" placeholder="Study Title (optional)" aria-label="Study title (optional)"><p class="err" id="i-err" role="alert" hidden></p>
    <button class="pill big" data-a="doimport">Import and Start Review</button>`);
  };

  function doImport() {
    const err = $("#i-err"), fail = m => { err.textContent = "Import failed: " + m; err.hidden = false; };
    if (isrc === "lichess") return fail("this demo can't reach Lichess. Paste PGN text instead.");
    try {
      const g = parsePGN($("#i-pgn").value), title = $("#i-title").value.trim() || g[0].title || "Imported Study";
      studies.push(mkStudy(title, g[0].side, g.map(x => ({ t: x.title, s: x.s }))));
      sel = studies.length - 1; practice = false; closeModal(); startSession();
    } catch (e) {
      fail(e.message);
    }
  }

  const textIn = (id, val, ph) => `<input id="${id}" value="${esc(val)}" aria-label="${ph}" autofocus>`;

  /* ---------- Action Handler Registry ---------- */
  const A = {
    close: closeModal, picker, more, about, import: importModal, doimport: doImport, analyze, skip, cont,
    pick: el => { sel = +el.dataset.i; practice = false; closeModal(); startSession(); },
    scope: () => { sel = -1; practice = false; closeModal(); startSession(); },
    sacts: el => studyActions(+el.dataset.i),
    practice: () => { practice = !practice; closeModal(); startSession(); },
    pause: () => { const s = tgt(); s.active = !s.active; closeModal(); startSession(); },
    restart: () => { st().lines.forEach(l => l.cards.forEach(c => { c.due = true; c.ivl = 0; c.lapses = 0; })); startSession(); },
    export: () => modal("Export PGN", `<pre class="pgn2" id="x-pgn" tabindex="0">${esc(toPGN(tgt()))}</pre><div class="cta2"><button class="pill" data-a="copy">Copy PGN</button></div>`),
    copy: el => {
      const txt = toPGN(tgt());
      (navigator.clipboard ? navigator.clipboard.writeText(txt) : Promise.reject()).then(
        () => el.textContent = "Copied",
        () => {
          const r = document.createRange(); r.selectNodeContents($("#x-pgn"));
          const s = getSelection(); s.removeAllRanges(); s.addRange(r);
          el.textContent = "Selected: press Ctrl+C";
        }
      );
    },
    rename: () => modal("Rename repertoire", `${textIn("r-in", tgt().name, "Repertoire name")}<div class="cta2"><button class="pill" data-a="dorename">Rename</button><button class="sk" data-a="close">Cancel</button></div>`),
    dorename: () => { const v = $("#r-in").value.trim(); if (v) tgt().name = v; closeModal(); head(); },
    delete: () => modal("Delete repertoire?", `<p class="pad">Delete ${esc(tgt().name)}? Its lines and review schedule are removed.</p><div class="cta2"><button class="sk" data-a="close">Cancel</button><button class="pill danger" data-a="dodelete">Delete</button></div>`),
    dodelete: () => { const i = sa; studies.splice(i, 1); sel = Math.min(sel, studies.length - 1); practice = false; closeModal(); startSession(); },
    isrc: el => {
      isrc = el.dataset.v;
      mo.querySelectorAll("[data-a=isrc]").forEach(b => b.setAttribute("aria-pressed", b === el));
      $("#i-file").hidden = isrc !== "file";
      $("#i-li").hidden = isrc !== "lichess";
    },
    theme: el => { set.theme = el.dataset.v === "true"; apply(); mo.querySelectorAll("[data-a=theme]").forEach(b => b.setAttribute("aria-pressed", b === el)); },
    accent: el => { set.accent = el.dataset.v; apply(); mo.querySelectorAll("[data-a=accent]").forEach(b => b.setAttribute("aria-pressed", b === el)); },
    ply: el => showPly(+el.dataset.i),
    aprev: () => showPly(an.i - 1),
    anext: () => showPly(an.i + 1),
    aback: () => startSession(),
    /* Library sheet's Settings row opens the full Settings modal. */
    settings: () => { closeModal(); settings(); },
    /* Settings handlers — segmented controls and switches */
    limit: el => { set.limit = +el.dataset.v; apply(); mo.querySelectorAll("[data-a=limit]").forEach(b => b.setAttribute("aria-pressed", b === el)); },
    retention: el => { set.retention = +el.dataset.v; apply(); el.closest(".sh").querySelectorAll("[data-a=retention]").forEach(b => { b.setAttribute("aria-pressed", b === el); b.classList.toggle("on", b === el); }); },
    scheduler: el => { set.scheduler = el.dataset.v; apply(); mo.querySelectorAll("[data-a=scheduler]").forEach(b => b.setAttribute("aria-pressed", b === el)); },
    showHistory: el => { set.showHistory = !set.showHistory; apply(); mo.querySelectorAll("[data-a=showHistory]").forEach(b => b.classList.toggle("on", set.showHistory)); },
    showArrows: el => { set.showArrows = !set.showArrows; apply(); mo.querySelectorAll("[data-a=showArrows]").forEach(b => b.classList.toggle("on", set.showArrows)); },
    showNotes: el => { set.showNotes = !set.showNotes; apply(); mo.querySelectorAll("[data-a=showNotes]").forEach(b => b.classList.toggle("on", set.showNotes)); },
    diagnostics: el => { set.diagnostics = !set.diagnostics; apply(); mo.querySelectorAll("[data-a=diagnostics]").forEach(b => b.classList.toggle("on", set.diagnostics)); },
    sound: el => { set.sound = !set.sound; apply(); mo.querySelectorAll("[data-a=sound]").forEach(b => b.classList.toggle("on", set.sound)); }
  };

  /* Theme and accent are applied the way the app applies them: as data attributes on the demo
     root, which is what the generated token file keys off. Keeping the mechanism identical means
     the app's own light/dark and four-accent rules apply here unchanged. */
  function apply() {
    host.dataset.theme = set.theme;
    if (set.accent) host.dataset.accent = set.accent;
    host.classList.toggle("nocoord", !set.coords);
    // showHistory controls whether the notation line renders move history
    host.classList.toggle("show-history", !!set.showHistory);
    // showArrows controls whether the board shows arrow/circle annotations
    host.classList.toggle("show-arrows", !!set.showArrows);
    // showNotes controls whether notes appear after a move
    host.classList.toggle("show-notes", !!set.showNotes);
    // diagnostics controls whether the HUD shows
    host.classList.toggle("diagnostics", !!set.diagnostics);
  }

  host.addEventListener("click", e => {
    if (e.target === mo) return closeModal();
    const a = e.target.closest("[data-a]");
    if (a && A[a.dataset.a]) A[a.dataset.a](a);
  });

  const onSetting = e => {
    const k = e.target.dataset.k;
    if (!k) return;
    set[k] = e.target.type === "checkbox" ? e.target.checked : +e.target.value;
    apply();
    if (k === "retention") $("#v-ret").textContent = set.retention + "%";
    if (k === "limit") {
      $("#v-lim").textContent = set.limit;
      if (e.type === "change") startSession();
    }
  };

  mo.addEventListener("input", onSetting);
  mo.addEventListener("change", e => {
    onSetting(e);
    if (e.target.id === "i-f" && e.target.files[0]) {
      e.target.files[0].text().then(t => $("#i-pgn").value = t);
    }
  });

  addEventListener("keydown", e => {
    if (!mo.hidden) {
      if (e.key === "Escape") closeModal();
      else if (e.key === "Enter" && e.target.id === "r-in") A.dorename();
      else if (e.key === "Tab") {
        const f = [...mo.querySelectorAll("button,input,textarea,a[href]")].filter(x => !x.hidden && x.offsetParent !== null),
          i = f.indexOf(document.activeElement);
        if (f.length && (e.shiftKey ? i <= 0 : i === f.length - 1)) {
          e.preventDefault();
          f[e.shiftKey ? f.length - 1 : 0].focus();
        }
      }
      return;
    }
    if (e.metaKey || e.ctrlKey || e.altKey || (document.activeElement !== document.body && !host.contains(document.activeElement)) || /INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)) return;
    if (an) {
      if (e.key === "ArrowLeft") showPly(an.i - 1);
      if (e.key === "ArrowRight") showPly(an.i + 1);
      return;
    }
    if (e.key.toLowerCase() === "s") skip();
    else if (e.key === " " && cur && cur.wait && !/BUTTON|A/.test(document.activeElement.tagName)) {
      e.preventDefault();
      cont();
    }
  });

  apply();
  startSession();
})();
