/* ChessSRS live demo — authentic port of Flutter ReviewScreen ("Diagram" identity).
   Board on the left with outer/inner coordinates, fixed regions on the right:
   Meta (Game 1, White to play), Notation Line with dashed blank, Answer/Note Slot, and Skip/Continue actions.
*/
(() => {
  const host = document.getElementById("app"); if (!host) return;
  host.dataset.screen = "review";
  host.dataset.phase = "prompt";
  host.classList.add("app");
  const { F, START, sq, nm, genB, compile, parsePGN, toPGN, nextInterval } = window.SRSEngine;
  const NS = "http://www.w3.org/2000/svg", $ = (s, c = host) => c.querySelector(s);
  const esc = s => String(s).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  const days = n => n === 1 ? "1 day" : n + " days";

  /** SAN for every ply of a line, via the same chess.js the page loads. */
  const sanOf = sanStr => {
    const toks = sanStr.split(/\s+/).filter(Boolean);
    const Chess = window.Chess;
    if (!Chess) return toks;                       // no rules engine: show the raw tokens
    const ch = new Chess(), out = [];
    for (const t of toks) {
      const mv = ch.move(t);
      if (!mv) break;
      out.push(mv.san);
    }
    return out;
  };

  /* ---------- study data ----------
     Chapter titles are "Game 1", "Game 2" and so on because that is what the app's importer
     produces: pgn_importer.dart falls back to `Game ${index + 1}` for any game in a PGN with no
     real chapter title, and the review screen's meta row shows `chapterTitle ?? studyTitle`.
     Descriptive chapter names invented here would be the one thing on screen the app itself can
     never produce from a PGN. */
  const PRESETS = [
    {
      name: "Queen Pawn Repertoire",
      side: "w",
      lines: [
        {
          t: "Game 1",
          s: "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 c4 Nbd2",
          note: "The French Defense: Advance Variation",
          noteSource: "From your study"
        },
        {
          t: "Game 2",
          s: "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Bd7 Be2 Nge7 Na3 cxd4 cxd4 Nf5 Nc2",
          note: "Solidity in the center with Bd7 and Be2",
          noteSource: "From your study"
        }
      ]
    },
    {
      name: "Sicilian Defense Repertoire",
      side: "b",
      lines: [
        {
          t: "Game 1",
          s: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6",
          note: "English Attack setup",
          noteSource: "From your study"
        }
      ]
    }
  ];

  const SAMPLE = `[Event "My Rep for White"]\n\n1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. c3 Nf6 5. d4 exd4 6. cxd4 Bb4+ 7. Nc3 Nxe4 8. O-O Bxc3 9. d5 Bf6 10. Re1 Ne7 *`;
  /* Accent list, fonts and motion timings all come from the app repo via assets/app-meta.js
     (generated by scripts/sync-design.js). Nothing here is written down twice: a new accent or
     a retuned duration in the app arrives here on the next sync. */
  const META = window.CHESSSRS_META || { accents: [], motion: {} };
  const ACC = META.accents;
  const MOTION = META.motion || {};
  const QUICK_ADVANCE_MS = MOTION.quietAdvanceMs ?? 560;
  const OPPONENT_REPLY_MS = MOTION.pieceMoveMs ?? 170;
  const set = { theme: "dark", accent: (ACC.find(a => a.default) || ACC[0])?.id, sound: false, coords: true, arrows: true, retention: 88, limit: 20, scheduler: "fsrs", showHistory: false, showArrows: true, showNotes: true, diagnostics: false, soundTheme: "Classic", masterVolume: 1 };
  let studies = [], uid = 0, sel = 0, practice = false, queue = [], cur = null, an = null, isrc = "file", sa = 0;

  const mkStudy = (name, side, lines) => {
    const s = { id: ++uid, name, side, active: true, lines: [] };
    for (const l of lines) {
      const m = compile(l.s), line = { t: l.t, s: l.s, note: l.note, noteSource: l.noteSource, m, san: sanOf(l.s), cards: [] };
      m.forEach((_, k) => {
        if ((k % 2 === 0) === (side === "w")) {
          line.cards.push({ k, line, due: true, ivl: 0, lapses: 0 });
        }
      });
      s.lines.push(line);
    }
    return s;
  };

  studies = PRESETS.map(p => mkStudy(p.name, p.side, p.lines));
  /* `sel` is the scope. One drawer per colour, opened by the matching square in the top bar
     (`_openColourDrawer`): a drawer lists only its own colour's studies, and tapping a square
     switches to that side's scope as well as opening its drawer. `sel` is a side string for a
     repertoire scope or an index for one study — the app always resolves the initial `all()` to a
     side the same way (White wins when the library holds any White chapter), so the demo starts
     there too rather than inventing an everywhere scope the UI can no longer produce. `scope()` is
     the list a session draws from, so the review loop never has to care which scope is active. */
  sel = studies.some(s => s.side === "w") ? "w" : "b";
  const st = () => (typeof sel === "number" && sel >= 0 ? studies[sel] : null);
  const scope = () => (typeof sel === "string" ? studies.filter(s => s.side === sel) : sel >= 0 ? [studies[sel]] : studies);
  const dueN = s => s ? s.lines.reduce((n, l) => n + l.cards.filter(c => c.due).length, 0) : 0;
  // Side scopes count active studies of that side only, like the app's sideProgress.
  const sideDue = side => studies.filter(s => s.side === side && s.active).reduce((n, s) => n + dueN(s), 0);
  /* The colour whose drawer is open and whose positions are being reviewed (`SrsTopBar.activeSide`):
     the side string in scope, the side of the single study in scope, White before anything loads. */
  const liveSide = () => (typeof sel === "string" ? sel : sel >= 0 && studies[sel] ? studies[sel].side : "w");
  /* `ReviewScopeDrawer.sideLabel`: one string shared by the squares, the drawer semantics and the
     study actions sheet's Create row, so the three can never disagree. Renames are caught by the
     scope-drawer parity test against `design/app-ui.json`. */
  const SIDE_LABEL = { w: "White repertoire", b: "Black repertoire" };
  /* The study a Study Actions sheet is acting on: the one it was opened for, falling back to
     the current scope. Actions in the app hang off a repertoire row, not off the session. */
  const tgt = () => studies[sa] || st() || studies[0];

  /* ---------- SVG Icons ---------- */

  /* ---------- Shell HTML: mirrors design/reference/index.html, except the top bar ----------
     The reference specimen still renders the old scope-name button; the app itself replaced it with
     the two colour squares (`SrsTopBar`), so the demo renders the squares and the square styles live
     in styles.css rather than in the generated reference stylesheet. */
  host.innerHTML = `
    <div class="statusbar" aria-hidden="true">
      <span>9:41</span>
      <svg viewBox="0 0 24 12"><rect x=".75" y=".75" width="20" height="10.5" rx="3" fill="none" stroke="currentColor" stroke-width="1.5"/><rect x="2.5" y="2.5" width="14" height="7" rx="1.6" fill="currentColor"/><rect x="21.5" y="4" width="1.8" height="4" rx=".9" fill="currentColor"/></svg>
    </div>

    <header class="topbar">
      <div class="sqs" role="group" aria-label="Repertoire colour">
        <button class="sq sq-w on" id="sqW" data-a="square" data-v="w" aria-label="White repertoire" aria-pressed="true" aria-haspopup="dialog"><i></i></button>
        <button class="sq sq-b" id="sqB" data-a="square" data-v="b" aria-label="Black repertoire" aria-pressed="false" aria-haspopup="dialog"><i></i></button>
      </div>
      <span class="due" id="due"><b>16</b> due</span>
      <span class="spacer"></span>
      <button class="icon-btn" id="moreBtn" aria-label="Library and settings" aria-haspopup="dialog">
        <svg viewBox="0 0 20 20" aria-hidden="true"><circle cx="4" cy="10" r="1.7"/><circle cx="10" cy="10" r="1.7"/><circle cx="16" cy="10" r="1.7"/></svg>
      </button>
    </header>

    <section class="view view-review" aria-label="Review">
      <div id="boardHost"></div>
      <aside class="side">
        <div class="meta">
          <span id="ctx"></span>
          <span class="turn"><i class="dot" id="turnDot"></i><span id="turnTxt">White to play</span></span>
        </div>
        <h2 class="line" id="line"></h2>
        <div class="slot">
          <div class="answer" id="answer" hidden>
            <div class="answer-move" id="ansMove"></div>
            <div class="answer-help">Play this move to continue. The position will come back soon.</div>
          </div>
          <blockquote class="note" id="note" hidden>
            <p id="noteText"></p>
            <small>From your study</small>
          </blockquote>
        </div>
        <div class="actions">
          <button class="text-btn" id="skipBtn">Skip <kbd>S</kbd></button>
          <button class="pill" id="contBtn" hidden>Continue <kbd>Space</kbd></button>
        </div>
      </aside>
      <div class="sr" id="live" role="status" aria-live="polite"></div>
    </section>

    <section class="view view-idle" aria-label="Nothing due">
      <div class="idle">
        <h1>Nothing due.</h1>
        <p class="next" id="idleNext"></p>
        <div class="idle-actions"></div>
      </div>
    </section>

    <section class="view view-settings" aria-label="Settings">
      <div class="set-head">
        <button class="text-btn" id="backBtn" style="margin-left:0;padding-left:8px">
          <svg viewBox="0 0 16 16" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M10 3 5 8l5 5"/></svg>
          Review
        </button>
      </div>
      <div class="set-col">
        <h1 id="setTitle">Settings</h1>
        <div id="settingsBody"></div>
      </div>
    </section>

    <div class="scrim" id="scrim"></div>

    <div class="sheet sheet-scope" id="sheetScope" role="dialog" aria-label="Choose what to review">
      <div class="grab"></div>
      <label class="search">
        <svg viewBox="0 0 18 18" aria-hidden="true"><circle cx="8" cy="8" r="5.2"/><path d="m12 12 4 4"/></svg>
        <input id="scopeSearch" type="text" placeholder="Search" autocomplete="off" aria-label="Search repertoires and openings">
      </label>
      <div class="list" id="scopeList"></div>
    </div>

    <div class="sheet sheet-library" id="sheetLib" role="dialog" aria-label="Library">
      <div class="grab"></div>
      <div class="list">
        <div class="lib-group">
          <button class="lib-row" data-lib="import"><span>Import PGN<small>From a file, pasted text or a Lichess study</small></span><svg viewBox="0 0 14 14"><path d="m5 2.5 4.5 4.5L5 11.5"/></svg></button>
        </div>
        <div class="lib-group">
          <button class="lib-row" data-lib="settings">Settings<svg viewBox="0 0 14 14"><path d="m5 2.5 4.5 4.5L5 11.5"/></svg></button>
          <button class="lib-row" data-lib="about">About and licences<svg viewBox="0 0 14 14"><path d="m5 2.5 4.5 4.5L5 11.5"/></svg></button>
        </div>
      </div>
    </div>

    <div class="toast" id="toast" role="status"></div>
  `;

  /* ---------- Board ---------- */
  /* The piece sprite. Each piece is drawn as three <use> layers — halo, line, fill — over one
     shared silhouette, so the 32 squares reference a single <g> per piece instead of inlining the
     geometry 96 times. `scripts/sync-design.js` lifts those silhouettes out of the app's own
     per-piece SVGs into `pieces.js` as PIECE_DEFS. It is injected here, after the shell markup has
     been written: `host.innerHTML` above replaces the demo's entire contents, so anything appended
     before it is discarded — which left every <use> resolving to nothing and the board empty. */
  if (window.PIECE_DEFS) {
    const sprite = document.createElementNS(NS, "svg");
    sprite.setAttribute("width", "0");
    sprite.setAttribute("height", "0");
    sprite.setAttribute("aria-hidden", "true");
    sprite.style.cssText = "position:absolute;width:0;height:0;overflow:hidden";
    sprite.innerHTML = `<defs>${window.PIECE_DEFS}</defs>`;
    host.appendChild(sprite);
  }

  const boardHost = $("#boardHost");
  const bdEl = document.createElement("div");
  bdEl.className = "board-wrap";
  bdEl.innerHTML = `<div class="coords-r" aria-hidden="true"></div><div class="board" id="bd" role="application" tabindex="0" aria-label="Chess board"><svg class="bg" viewBox="0 0 80 80" preserveAspectRatio="none"><defs><pattern id="hatch" patternUnits="userSpaceOnUse" width=".9" height=".9" patternTransform="rotate(45)"><rect width=".1" height=".9"/></pattern></defs><rect class="sq-l" width="80" height="80"/><path class="sq-d" d=""/><path d="" fill="url(#hatch)"/><g class="hl"></g></svg><div class="pieces"></div><svg class="arrow-layer" viewBox="0 0 80 80"></svg><div class="coords-in"></div></div><div class="coords-f" aria-hidden="true"></div>`;
  boardHost.appendChild(bdEl);

  const bd = $("#bd"), pcsLayer = bd.querySelector(".pieces"), bgSvg = bd.querySelector(".bg"), hlLayer = bd.querySelector(".hl"), arrowLayer = bd.querySelector(".arrow-layer");
  /* The coordinate gutters are siblings of `.board` inside `.board-wrap`, and the inside labels are
     its own children — SrsBoardWithCoordinates draws ranks/files outside on wide layouts and inside
     on narrow ones, and the reference CSS switches which pair is displayed at the same breakpoint. */
  const coordR = bdEl.querySelector(".coords-r"), coordF = bdEl.querySelector(".coords-f"), coordIn = bd.querySelector(".coords-in");
  let flip = false, pcs = [], selSq = -1, dests = [], drag = null, enabled = false, timer = 0, user = "w", lastMove = null, ac = null, kb = -1;
  const at = i => pcs.find(p => p.i === i), D = i => [flip ? 7 - (i & 7) : i & 7, flip ? 7 - (i >> 3) : i >> 3];

  /* Piece rendering, layer for layer as the app draws it: the silhouette three times over — halo,
     line, fill — then the detail strokes, which the app paints with `currentColor` so a knight's
     eye and mane, a rook's crenellation bar and a king's base curve follow the piece's own colour.
     All four groups come out of scripts/sync-design.js; the colours are CSS. */
  const art = ch => {
    const t = ch.toUpperCase(), isWhite = ch < "a";
    return `<svg class="pc ${isWhite ? "w" : "b"}" viewBox="5 2 90 90" aria-hidden="true"><use href="#pc-${t}" class="halo"/><use href="#pc-${t}" class="line"/><use href="#pc-${t}" class="fill"/><use href="#pd-${t}" class="det"/></svg>`;
  };

  const place = (p, i) => { p.i = i; const [c, r] = D(i); p.el.style.transform = `translate(${c * 100}%,${r * 100}%)`; };
  const labels = () => {
    coordR.innerHTML = [...Array(8)].map((_, r) => `<span>${flip ? r + 1 : 8 - r}</span>`).join("");
    coordF.innerHTML = [...Array(8)].map((_, c) => `<span>${F[flip ? 7 - c : c]}</span>`).join("");
    let inside = "";
    for (let c = 0; c < 8; c++) inside += `<span class="cf" style="left:${c * 12.5}%;top:87.5%">${F[flip ? 7 - c : c]}</span>`;
    for (let r = 0; r < 8; r++) inside += `<span class="cr" style="left:0;top:${r * 12.5}%">${flip ? r + 1 : 8 - r}</span>`;
    coordIn.innerHTML = inside;
  };

  function setup(fen, f) {
    pcsLayer.innerHTML = ""; pcs = []; flip = f; labels(); selSq = -1; dests = []; mark(); arrow();
    fen.split("/").forEach((row, r) => {
      let c = 0;
      for (const ch of row) {
        if (+ch) { c += +ch; continue; }
        const el = document.createElement("div");
        el.className = "pc-wrap";
        el.innerHTML = art(ch);
        pcsLayer.append(el);
        const p = { ch, el, i: 0 };
        place(p, r * 8 + c);
        pcs.push(p);
        c++;
      }
    });
    // Draw board squares into the background SVG
    let dark = "";
    for (let f = 0; f < 8; f++) {
      for (let r = 0; r < 8; r++) {
        if ((f + r) % 2 === 1) dark += `M${f * 10} ${r * 10}h10v10h-10z`;
      }
    }
    bgSvg.querySelector(".sq-d").setAttribute("d", dark);
    bgSvg.querySelector("path[fill='url(#hatch)']").setAttribute("d", dark);
  }

  function move(f, t) {
    const p = at(f), c = at(t), k = p.ch.toLowerCase(), drop = x => { if (x) { x.el.remove(); pcs.splice(pcs.indexOf(x), 1); } };
    drop(c);
    if (k === "p" && (f & 7) !== (t & 7) && !c) drop(at((f >> 3) * 8 + (t & 7)));
    if (k === "k" && Math.abs((f & 7) - (t & 7)) === 2) {
      const r = at((f >> 3) * 8 + (t > f ? 7 : 0));
      r && place(r, (f >> 3) * 8 + (t > f ? 5 : 3));
    }
    if (k === "p" && (t >> 3 === 0 || t >> 3 === 7)) {
      p.ch = p.ch < "a" ? "Q" : "q";
      p.el.innerHTML = art(p.ch);
    }
    place(p, t);
  }

  const gen = i => {
    const b = Array(64).fill("");
    pcs.forEach(p => { b[p.i] = p.ch; });
    return genB(b, i);
  };

  function mark(last, selected) {
    let h = "";
    (last || []).forEach(i => {
      const [c, r] = D(i);
      h += `<rect x="${c * 10}" y="${r * 10}" width="10" height="10" class="last"/>`;
    });
    if (selected >= 0) {
      const [c, r] = D(selected);
      h += `<rect x="${c * 10}" y="${r * 10}" width="10" height="10" class="sel"/>`;
    }
    hlLayer.innerHTML = h;
  }

  function arrow(m) {
    arrowLayer.innerHTML = "";
    if (!m || !set.arrows) return;
    const P = i => D(i).map(v => v + .5), [x1, y1] = P(sq(m.slice(0, 2))), [x2, y2] = P(sq(m.slice(2, 4)));
    const dx = x2 - x1, dy = y2 - y1;
    const cx = (x1 + x2) / 2 - dy * .14, cy = (y1 + y2) / 2 + dx * .14;
    const ux = x2 - cx, uy = y2 - cy, l = Math.hypot(ux, uy), hx = ux / l, hy = uy / l, h = .44;
    arrowLayer.innerHTML = `<path class="arr" d="M${x1 * 10} ${y1 * 10}Q${cx * 10} ${cy * 10} ${(x2 - hx * h * .8) * 10} ${(y2 - hy * h * .8) * 10}"/><path class="arr-head" d="M${x2 * 10} ${y2 * 10}L${(x2 - hx * h - hy * .25) * 10} ${(y2 - hy * h + hx * .25) * 10}L${(x2 - hx * h + hy * .25) * 10} ${(y2 - hy * h - hx * .25) * 10}Z"/>`;
  }

  const snapTo = (L, n, side) => {
    pcsLayer.classList.add("snap"); setup(START, side === "b");
    for (let j = 0; j < n; j++) move(sq(L.m[j].slice(0, 2)), sq(L.m[j].slice(2, 4)));
    lastMove = n ? [sq(L.m[n - 1].slice(0, 2)), sq(L.m[n - 1].slice(2, 4))] : null;
    mark(lastMove, -1);
    setTimeout(() => pcsLayer.classList.remove("snap"), 40);
  };

  /* ---------- Pointer Input ---------- */
  const idx = e => {
    const r = bd.getBoundingClientRect(), cl = v => Math.min(7, Math.max(0, v)),
      c = cl(Math.floor((e.clientX - r.left) / r.width * 8)), w = cl(Math.floor((e.clientY - r.top) / r.height * 8));
    return flip ? (7 - w) * 8 + 7 - c : w * 8 + c;
  };
  const mine = p => (p.ch < "a") === (user === "w");
  const select = i => { selSq = i; dests = i < 0 ? [] : gen(i); mark(lastMove, i); };

  bd.addEventListener("pointerdown", e => {
    if (!enabled) return;
    const i = idx(e), p = at(i);
    if (selSq >= 0 && dests.includes(i)) return attempt(selSq, i);
    if (p && mine(p)) {
      select(i);
      drag = { p, from: i, x: e.clientX, y: e.clientY, moved: false };
      // `.drag` is what lifts the piece (scale 1.08), raises it above the others (z-index 6) and
      // switches the cursor. demo-reference.css has always defined it; nothing was adding it, so a
      // dragged piece painted under its neighbours and gave no pick-up feedback at all.
      p.el.classList.add("drag");
      pcsLayer.append(p.el);
      bd.setPointerCapture(e.pointerId);
    } else {
      select(-1);
    }
  });

  bd.addEventListener("pointermove", e => {
    if (!drag) return;
    if (Math.hypot(e.clientX - drag.x, e.clientY - drag.y) > 5) drag.moved = true;
    if (drag.moved) {
      const r = bd.getBoundingClientRect(), s = r.width / 8;
      // place() parks a piece with translate(<col*100>%, <row*100>%), so the drag offset has to be in
      // those same units. Writing it in pixels left the piece sitting on a8 with a few pixels of
      // offset while the destination highlight followed the cursor: the move resolved correctly on
      // pointerup, but the piece never appeared to move. That is what made dragging look broken.
      drag.p.el.style.transform = `translate(${((e.clientX - r.left) / s - .5) * 100}%,${((e.clientY - r.top) / s - .5) * 100}%)`;
    }
  });

  const release = (e, cancel) => {
    if (!drag) return;
    const { p, from, moved } = drag;
    drag = null;
    p.el.classList.remove("drag"); // restores the transition, so place() animates it home
    const i = cancel ? -1 : idx(e);
    if (moved && dests.includes(i)) attempt(from, i);
    else { place(p, from); if (moved) select(-1); }
  };
  bd.addEventListener("pointerup", e => release(e));
  bd.addEventListener("pointercancel", e => release(e, true));

  /* ---------- Keyboard Input ---------- */
  const NAMES = { k: "king", q: "queen", r: "rook", b: "bishop", n: "knight", p: "pawn" };
  const desc = i => {
    const p = at(i);
    return nm(i) + (p ? `, ${p.ch < "a" ? "white" : "black"} ${NAMES[p.ch.toLowerCase()]}` : ", empty");
  };

  bd.addEventListener("focus", () => {
    if (kb < 0) kb = sq(user === "w" ? "e2" : "e7");
    mark(lastMove, selSq);
    say(desc(kb));
  });
  bd.addEventListener("blur", () => mark(lastMove, selSq));
  bd.addEventListener("keydown", e => {
    const arrows = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, -1], ArrowDown: [0, 1] };
    if (arrows[e.key]) {
      e.preventDefault();
      const [c, r] = D(kb), nc = Math.min(7, Math.max(0, c + arrows[e.key][0])), nr = Math.min(7, Math.max(0, r + arrows[e.key][1]));
      kb = flip ? (7 - nr) * 8 + 7 - nc : nr * 8 + nc;
      mark(lastMove, selSq);
      say(desc(kb));
      return;
    }
    if (e.key === "Escape") { select(-1); say("Selection cleared"); return; }
    // Enter only. review_screen.dart wraps the screen in CallbackShortcuts where Space is Continue
    // and S is Skip, and the app's board — chessground 10.3.0 — handles no keys at all (only
    // onTapDown/onPanStart/onPanUpdate), so nothing there can consume a key first. Binding Space
    // here meant that as soon as the board had focus, i.e. after any click on it, Space moved the
    // cursor instead of continuing and overwrote the verdict in the live region.
    if (e.key !== "Enter") return;
    e.preventDefault();
    if (!enabled) return;
    const p = at(kb);
    if (selSq >= 0 && dests.includes(kb)) return attempt(selSq, kb);
    if (p && mine(p)) {
      select(kb);
      say(`${desc(kb)} selected. ${dests.length} squares to move to.`);
    } else {
      select(-1);
      say(`${desc(kb)}. Not one of your pieces.`);
    }
  });

  /* ---------- Review Session Engine ---------- */
  const say = t => $("#live").textContent = t;
  const view = n => {
    [".view-review", ".view-idle", ".view-settings"].forEach(sel => { $(sel).hidden = true; });
    if (n === "rev") host.dataset.screen = "review", $(".view-review").hidden = false;
    else if (n === "empty") host.dataset.screen = "idle", $(".view-idle").hidden = false;
    else if (n === "settings") host.dataset.screen = "settings", $(".view-settings").hidden = false;
  };

  function head() {
    const live = scope().filter(x => x.active);
    /* The squares say the same two things forever (`SrsTopBar`): the active side carries the accent
       ring, and the due count beside them is that side's. There is no scope-name button any more. */
    const side = liveSide();
    for (const [v, id] of [["w", "#sqW"], ["b", "#sqB"]]) {
      const on = v === side;
      $(id).classList.toggle("on", on);
      $(id).setAttribute("aria-pressed", on);
    }
    const dueCount = !studies.length ? 0 : !live.length ? 0 : practice ? 0 : sideDue(side);
    $("#due").innerHTML = practice ? `<b>Practice</b>` : `<b>${dueCount}</b> due`;
  }

  const turn = () => {
    const isW = user === "w";
    $("#turnTxt").textContent = (isW ? "White" : "Black") + " to play" + (practice ? " · Practice" : "");
    const dot = $("#turnDot");
    if (dot) dot.className = "dot" + (isW ? "" : " b");
  };

  function startSession() {
    clearTimeout(timer); cur = null; an = null; enabled = false;
    queue = [];
    for (const s of scope()) {
      if (!s.active) continue;
      for (const c of s.lines.flatMap(l => l.cards)) c.s = s;
    }
    const all = scope().filter(s => s.active).flatMap(s => s.lines.flatMap(l => l.cards));
    queue = (practice ? all : all.filter(c => c.due)).slice(0, set.limit);
    head();
    queue.length ? present(queue[0]) : empty();
  }

  function present(c) {
    clearTimeout(timer);
    const s = c.s || st(), L = c.line, again = cur && cur.line === L && c.k === cur.k + 2;
    view("rev");
    user = s.side;
    enabled = false;
    $("#ctx").textContent = L.t;
    $("#line").innerHTML = notationHTML(L.san.slice(0, c.k), null);
    $("#note").hidden = true;
    $("#answer").hidden = true;
    $("#contBtn").hidden = true;
    $("#skipBtn").hidden = false;
    // A previous lapse may have renamed it; every new card starts by asking.
    $("#skipBtn").innerHTML = `Skip <kbd>S</kbd>`;
    arrow();
    head();

    const go = () => { cur = { c, line: L, missed: false, wait: false }; enabled = true; turn(); };
    if (again) {
      play(L.m[cur.c.k + 1]);
      timer = setTimeout(go, OPPONENT_REPLY_MS * 2 + 90);
    } else {
      snapTo(L, c.k, s.side);
      go();
    }
  }

  function play(m) {
    const f = sq(m.slice(0, 2)), t = sq(m.slice(2, 4));
    move(f, t);
    lastMove = [f, t];
    mark(lastMove, -1);
    ping();
  }

  function ping() {
    if (!set.sound) return;
    try {
      ac = ac || new (window.AudioContext || window.webkitAudioContext)();
      const o = ac.createOscillator(), g = ac.createGain();
      o.frequency.value = 620; g.gain.value = .04;
      o.connect(g); g.connect(ac.destination);
      o.start(); o.stop(ac.currentTime + .05);
    } catch {}
  }

  const revealSan = () => {
    const k = cur ? cur.c.k : -1;
    return k >= 0 && cur.line.san[k] ? cur.line.san[k] : "";
  };

  function reveal(m) {
    if (!m) {
      arrow();
      $("#answer").hidden = true;
      return;
    }
    arrow(m);
    const sanText = revealSan() || m.slice(2, 4);
    $("#ansMove").innerHTML = sanFig(sanText);
    $("#answer").hidden = false;
    say(`Play ${sanText} to continue.`);
  }

  function rate(c, ok) {
    if (practice) return;
    if (ok) {
      c.ivl = nextInterval(c.ivl, set.retention);
      c.due = false;
    } else {
      c.lapses++;
      c.ivl = 0;
      c.due = true;
    }
    head();
  }

  function miss() {
    if (!cur.missed) {
      cur.missed = true;
      rate(cur.c, false);
    }
  }

  /* ---------- Notation ----------
     Mirrors SrsNotationLine: completed move *pairs* (so a number never wraps away from its
     move), the line truncated to the last 8 plies behind a leading ellipsis, and the decision
     slot drawn as either the dashed blank or the answer in the accent. A leading piece letter is
     swapped for its figurine, as SrsSan does. */
  const FIG = window.FIGURINES || {};

  const sanFig = san => {
    if (!san) return "";
    const f = FIG[san[0]];
    if (!f) return esc(san);
    return `<svg class="fig" viewBox="${f.vb}" aria-hidden="true">${f.body}</svg>${esc(san.slice(1))}`;
  };

  /**
   * @param history  SAN of every ply before the decision
   * @param answer   SAN to show in the slot, or null to show the dashed blank
   */
  function notationHTML(history, answer) {
    let startPly = 0, visible = history;
    if (history.length > 8) {
      // Start on an even ply so the line opens on a move number rather than mid-pair, which is
      // what the leading ellipsis is there to explain.
      const excess = history.length - 8;
      startPly = excess % 2 === 0 ? excess : excess - 1;
      visible = history.slice(startPly);
    }
    const n = visible.length;
    const blackToMove = n % 2 === 1;
    const completed = blackToMove ? n - 1 : n;
    const slot = answer
      ? `<span class="mv fill">${sanFig(answer)}</span>`
      : `<span class="blank"></span>`;

    let h = startPly > 0 ? `<span class="num">…</span>` : "";
    for (let i = 0; i < completed; i += 2) {
      const num = Math.floor((startPly + i) / 2) + 1;
      h += `<span class="pair"><span class="num">${num}.</span><span class="mv">${sanFig(visible[i])}</span>` +
        (i + 1 < n ? `<span class="mv">${sanFig(visible[i + 1])}</span>` : "") + `</span>`;
    }
    const decisionNumber = Math.floor((startPly + n) / 2) + 1;
    const head = `<span class="num">${decisionNumber}.</span>`;
    h += blackToMove
      ? `<span class="pair">${head}<span class="mv">${sanFig(visible[n - 1])}</span>${slot}</span>`
      : `<span class="pair">${head}${slot}</span>`;
    return h;
  }

  function attempt(f, t) {
    select(-1);
    const want = cur.line.m[cur.c.k];
    if (nm(f) + nm(t) === want.slice(0, 4)) {
      move(f, t);
      lastMove = [f, t];
      mark(lastMove, -1);
      ping();
      enabled = false;
      reveal();

      // Fill the decision slot. The app reveals `expectedMoves.first.san` — the repertoire
      // move, not whatever was played — so a transposition still shows what the app would.
      const sanMove = cur.line.san[cur.c.k] || want.slice(2, 4);
      $("#line").innerHTML = notationHTML(cur.line.san.slice(0, cur.c.k), sanMove);

      // Line-level notes are chapter context, not per-move PGN comments:
      // per the Flutter app (_hasAnnotationsOrShapes on the prompt comment),
      // they must not pause auto-advancement. Only a lapse waits for Continue.
      // The turn row is left alone here. In the app it only ever reads "White to play" or
      // "Black to play" — the review interval is shown nowhere on screen, and the verdict is
      // carried to screen readers by a visually hidden live region. Overwriting this row with
      // "Remembered · back in 3 days" put text on the app's quiet-by-design surface.
      if (cur.missed) {
        cur.wait = true;
        $("#skipBtn").hidden = true;
        $("#contBtn").hidden = false;
        // Lapse + comment in the app shows Answer + Note together.
        if (cur.line.note) {
          $("#noteText").textContent = cur.line.note;
          $("#note").hidden = false;
        }
        say(`Correct. ${sanMove}.`);
      } else {
        rate(cur.c, true);
        say(`Correct. ${sanMove}.`);
        timer = setTimeout(next, QUICK_ADVANCE_MS);
      }
    } else {
      miss();
      reveal(want);
      if (cur.line.note) {
        $("#noteText").textContent = cur.line.note;
        $("#note").hidden = false;
      }
      lapseUI();
      place(at(f), f);
      // The app's wording, verbatim: review_screen.dart's _verdictAnnouncement.
      say(`Not this move. The study move is ${revealSan()}.`);
    }
  }

  const skip = () => {
    if (enabled && cur) {
      miss();
      reveal(cur.line.m[cur.c.k]);
      if (cur.line.note) {
        $("#noteText").textContent = cur.line.note;
        $("#note").hidden = false;
      }
      lapseUI();
    }
  };

  /* Once recall has failed, "Skip" mislabels what is left: the app swaps the action to
     `Reveal answer` (same S shortcut), which plays the study move on the learner's behalf through
     the normal retry path. The lapse already stands, so this changes the flow, not the grade. */
  const lapseUI = () => {
    $("#skipBtn").innerHTML = `Reveal answer <kbd>S</kbd>`;
  };

  const revealAnswer = () => {
    if (!(enabled && cur?.missed && !cur?.wait)) return;
    const want = cur.line.m[cur.c.k];
    const f = sq(want.slice(0, 2)), t = sq(want.slice(2, 4));
    move(f, t);
    lastMove = [f, t];
    mark(lastMove, -1);
    ping();
    const sanMove = cur.line.san[cur.c.k] || want.slice(2, 4);
    $("#line").innerHTML = notationHTML(cur.line.san.slice(0, cur.c.k), sanMove);
    cur.wait = true;
    $("#skipBtn").hidden = true;
    $("#contBtn").hidden = false;
    if (cur.line.note) {
      $("#noteText").textContent = cur.line.note;
      $("#note").hidden = false;
    }
    say(`Correct. ${sanMove}.`);
  };

  /* S follows the visible action: before any lapse it skips, in a lapse it reveals, and once the
     card is awaiting Continue it does nothing. */
  const pressS = () => {
    if (!(enabled && cur) || cur.wait) return;
    if (cur.missed) revealAnswer();
    else skip();
  };

  const cont = () => {
    if (cur?.wait) next();
  };

  function next() {
    const done = queue.shift();
    if (cur.missed && !practice) queue.push(done);
    head();
    queue.length ? present(queue[0]) : empty();
  }

  /* The review screen's nothing-due state. The app's title is `Nothing due.` — or `Daily limit
     reached.` — and there is deliberately no third "paused" state: a suspended study shows the same
     nothing-due screen, and Resume lives in the scope drawer's options button. An earlier version
     here invented a `Paused` headline with its own Resume button, which is a screen the app cannot
     produce; `tests/e2e/app-parity.spec.js` now pins these strings to `design/app-ui.json`.

     The one branch the app answers on a separate first-run screen is "no studies at all". This demo
     does not port that screen, but it uses its words rather than inventing a headline, and keeps
     the import affordance — without it, a visitor who deleted everything would be stuck. */
  function empty() {
    enabled = false; cur = null; select(-1); arrow();
    view("empty"); head();
    let h;
    if (!studies.length) {
      h = `<h1>Bring your study.</h1><p class="next">Import a PGN or a Lichess study. Everything stays on this device, and reviews work offline.</p>` +
        `<div class="idle-actions"><button class="pill" data-a="import">Import a PGN</button></div>`;
    } else {
      const live = scope().filter(x => x.active);
      const iv = live.flatMap(x => x.lines.flatMap(l => l.cards.map(c => c.ivl))).filter(x => x > 0);
      const when = iv.length ? " " + days(Math.min(...iv)) + "." : " will appear automatically.";
      h = `<h1>Nothing due.</h1><p class="next">Next review${when}</p>` +
        `<div class="idle-actions"><button class="pill" data-a="practice">Practice</button><button class="link" data-a="choose">Choose a study</button></div>` +
        `<p class="foot">Practice never changes your schedule.</p>`;
    }
    $(".idle").innerHTML = h;
  }

  /* ---------- Analyze View ---------- */
  function showPly(i) {
    an.i = Math.max(0, Math.min(an.L.m.length, i));
    snapTo(an.L, an.i, an.side);
    drawAn();
  }

  /* Analyze renders into the settings shell rather than replacing it. The shell's #backBtn carries
     a listener attached once at startup, and #settingsBody is what every other secondary screen
     writes into — overwriting the section would detach both, so every later screen (settings,
     export, rename, import) would render into nothing. */
  function drawAn() {
    const t = an.L.s.split(" ");
    $("#setTitle").textContent = an.L.t;
    $("#settingsBody").innerHTML = `<div class="t-san">${t.map((x, i) => (i % 2 ? "" : `<span class="num">${Math.floor(i / 2) + 1}.</span>`) + `<button data-a="ply" data-i="${i + 1}" class="ply${an.i === i + 1 ? " on" : ""}">${esc(x)}</button>`).join("")}</div><div class="idle-actions"><button class="text-btn" data-a="aprev" aria-label="Previous move">‹</button><button class="text-btn" data-a="anext" aria-label="Next move">›</button></div>`;
  }

  /* Analyze, export, rename, delete and import all leave the sheet they were opened from: the app
     pops the Study Actions dialog and the scope drawer before pushing the next screen
     (review_scope_drawer.dart: `Navigator.of(dialogContext).pop()` then `Navigator.of(context).pop()`).
     Leaving the scrim up would put a modal barrier over the screen that replaced it. */
  function analyze() {
    // Actions hang off a repertoire row, not off the session: analyze the sheet's target, which is
    // the study in scope when the sheet was opened for the current one. `st()` alone would be null
    // for a side scope.
    const s = tgt();
    const L = cur ? cur.line : s.lines[0];
    // Every queued card carries its study (`c.s`), so mid-review analysis orients by the position
    // on screen; otherwise by the sheet's target study. Either way it is a real side, never null.
    const side = (cur?.c?.s ? cur.c.s : s).side;
    closeSheet();
    clearTimeout(timer);
    cur = null; enabled = false; arrow();
    an = { L, i: 0, side };
    showPly(0);
    view("settings");
  }

  /* ---------- Modals / Sheets ---------- */
  function openSheet(id) {
    $("#scrim").classList.add("open");
    $(`#${id}`).classList.add("open");
  }

  function closeSheet() {
    $("#scrim").classList.remove("open");
    $(".sheet.open")?.classList.remove("open");
  }

  /* One drawer per colour, opened by the matching square (`ReviewScopeDrawer.show`). A drawer lists
     only its own colour's studies under Studies — the demo ports no openings, so the Openings group
     stays hidden exactly the way the app hides an empty group — then the full-width Import PGN pill
     (`SrsPillButton`, expanded). The colour is never spelled out inside: the square that opened the
     drawer already says which one this is.

     The search field filters by study title, and a query with no matches gets the app's empty state
     rather than an empty list. A suspended study keeps its numeral — pausing removes it from the
     review pool, it does not reset its schedule — and the app swaps the sub-line's figure for
     `Paused` and recolours the name and numeral to ink3 (`.row.paused`) rather than hiding either. */
  let drawerSide = "w";
  const memBar = s => {
    const all = s.lines.flatMap(l => l.cards);
    const learned = all.filter(c => c.ivl > 0).length;
    const due = all.filter(c => c.due).length;
    return `<span class="mem"><i class="m-ret" style="flex:${Math.max(0, learned - due)}"></i><i class="m-lrn" style="flex:${due}"></i><i class="m-new" style="flex:${Math.max(0, all.length - learned)}"></i></span>`;
  };

  const scopeRow = (attrs, name, due, study, paused, trail = "") =>
    `<div class="row${paused ? " paused" : ""}${due === 0 ? " zero" : ""}" ${attrs}>` +
    `<span class="row-main"><span class="row-name">${esc(name)}</span>` +
    `<span class="row-sub">${memBar(study)}<span>${paused ? "Paused" : study.lines.flatMap(l => l.cards).length + " positions"}</span></span></span>` +
    `<span class="row-due"><b>${due}</b> <i>due</i></span>${trail}</div>`;

  const options = i => `<button class="icon-btn" data-a="sacts" data-i="${i}" aria-label="Study options"><svg viewBox="0 0 20 20"><circle cx="4" cy="10" r="1.7"/><circle cx="10" cy="10" r="1.7"/><circle cx="16" cy="10" r="1.7"/></svg></button>`;
  const picker = side => {
    drawerSide = side;
    const q = $("#scopeSearch").value.trim().toLowerCase();
    const list = studies.map((s, i) => ({ s, i })).filter(({ s }) => s.side === side && (!q || s.name.toLowerCase().includes(q)));
    let h = `<div class="list">`;
    if (q && !list.length) h += `<div class="no-results">Nothing matches “${esc($("#scopeSearch").value.trim())}”.</div>`;
    else {
      if (list.length) {
        h += `<div class="lib-group"><div class="group-title">Studies</div>` +
          list.map(({ s, i }) => scopeRow(`data-a="pick" data-i="${i}" aria-current="${sel === i}"`, s.name, dueN(s), s, !s.active, options(i))).join("") +
          `</div>`;
      }
    }
    h += `<div class="imp"><button class="pill" data-a="import">Import PGN</button></div></div>`;
    $("#scopeList").innerHTML = h;
    openSheet("sheetScope");
  };

  /* The overflow button opens the Library sheet, which in the app carries two rows under a
     "Preferences" group header and nothing else (library_sheet.dart). Study-level actions are not
     here: they live in StudyActionsSheet, reached from a study's options button in the scope
     list — see `studyActions`. */
  const more = () => {
    $("#sheetLib .list").innerHTML = `<div class="lib-group"><div class="group-title">Preferences</div>` +
      `<button class="lib-row" data-a="settings"><span>Settings<small>Review, board, engine, and sound</small></span><svg viewBox="0 0 14 14"><path d="m5 2.5 4.5 4.5L5 11.5"/></svg></button>` +
      `<button class="lib-row" data-a="about"><span>About and licences</span><svg viewBox="0 0 14 14"><path d="m5 2.5 4.5 4.5L5 11.5"/></svg></button></div>`;
    openSheet("sheetLib");
  };

  /* StudyActionsSheet: four hairline-separated groups, in the app's order and wording, with the
     app's subtitles — and no title, no chevrons (§12 says "no icons"). First is the row this whole
     sheet exists for: a repertoire in the wrong colour is the most common reason the other drawer
     is empty, and `Create …` fixes it in one tap. Every label and subtitle is pinned to
     `design/app-ui.json` by the study-actions parity test. */
  function studyActions(i) {
    const s = studies[i];
    if (!s) return;
    sa = i;
    closeSheet();
    const other = s.side === "w" ? "b" : "w";
    const act = s.active;
    const sub = t => `<small>${t}</small>`;
    $("#sheetScope .list").innerHTML =
      `<div class="lib-group"><button class="lib-row" data-a="create"><span>Create ${SIDE_LABEL[other]}${sub("Same positions, in the other drawer")}</span></button></div>` +
      `<div class="lib-group"><button class="lib-row" data-a="analyze"><span>Analyze${sub("Browse moves and variations")}</span></button>` +
      `<button class="lib-row" data-a="practice"><span>${practice ? "End practice" : "Practice"}${sub("Drill lines without changing your schedule")}</span></button></div>` +
      `<div class="lib-group"><button class="lib-row" data-a="export"><span>Export PGN${sub("Share or copy standard PGN notation")}</span></button>` +
      `<button class="lib-row" data-a="pause"><span>${act ? "Pause" : "Resume"}${sub(act ? "Suspend from active review pool" : "Activate in review pool")}</span></button></div>` +
      `<div class="lib-group"><button class="lib-row" data-a="rename"><span>Rename</span></button>` +
      `<button class="lib-row" data-a="delete"><span>Delete</span></button></div>`;
    openSheet("sheetScope");
  }

  const seg = (opts, val, onChange, name) => {
    const b = Object.entries(opts).map(([k, v]) => `<button data-a="${onChange}" data-v="${k}" aria-pressed="${k == val}">${v}</button>`).join("");
    return `<div class="seg" data-n="${name}">${b}</div>`;
  };

  const sw = (k, label) => `<button class="tog" role="switch" aria-checked="${set[k]}" data-a="${k}" aria-label="${label}"></button>`;

  const accentDots = () => `<div class="accents">${ACC.map(a => `<button class="dotbtn${a.id === set.accent ? " on" : ""}" data-a="accent" data-v="${a.id}" aria-label="${a.name}" aria-pressed="${a.id === set.accent}" style="--c:${a[set.theme] || a.dark}"></button>`).join("")}</div>`;

  const sr = (label, help, control) => `<div class="set-row"><div><div class="set-label">${label}</div>${help ? `<div class="set-help">${help}</div>` : ""}</div><div class="sr-trail">${control}</div></div>`;

  /* SrsSettingsScreen groups its rows under uppercase headers, and carries the header's type
     inline rather than as a named style (_buildSectionHeader: 11.5px/w700/letter-spacing 1.1/ink3,
     uppercased). Reproduced the same way here, because the demo's stylesheet is generated
     verbatim from the app's and must not be hand-edited. Only the sections this demo implements
     appear; the rest of the app's navigate to screens that are not ported. */
  const section = (title, rows) =>
    `<h2 style="padding:28px 0 8px;font:700 11.5px var(--font-ui);letter-spacing:1.1px;color:var(--ink3);text-transform:uppercase">${esc(title)}</h2><div class="set-group">${rows.join("")}</div>`;

  const settings = () => {
    closeSheet();
    $("#setTitle").textContent = "Settings";
    $("#settingsBody").innerHTML = [
      section("Review & Spaced Repetition", [
        sr("Daily limit", "Positions reviewed per day.", seg({25:"25",50:"50",100:"100",150:"150",200:"200",0:"None"}, set.limit, "limit")),
        sr("Target retention", "Higher means more reviews. 88% suits most players; 95% is for tournament preparation.", seg({0.80:"80%",0.85:"85%",0.88:"88%",0.90:"90%",0.95:"95%"}, set.retention, "retention")),
        sr("Scheduling algorithm", "FSRS adapts to how well you remember each position.", seg({fsrs:"FSRS",simple:"Simple",easeScaling:"Ease"}, set.scheduler || "fsrs", "scheduler")),
        sr("Show move notation", "Display preceding moves (e.g. 1. e4 e5) in the review screen.", sw("showHistory", "Show move notation")),
        sr("Show arrows and circles", "Drawn from your study, only after you answer.", sw("showArrows", "Show arrows and circles")),
        sr("Show notes after a move", "Comments from your study appear once you have answered.", sw("showNotes", "Show notes after a move")),
        sr("Review Diagnostics HUD", "Show real-time FSRS retrievability, stability, and difficulty HUD in review.", sw("diagnostics", "Review Diagnostics HUD")),
      ]),
      section("Appearance", [
        sr("Theme", "", seg({false:"Light",true:"Dark"}, set.theme === "dark", "theme")),
        sr("Accent", "Colour of the correct move arrow and selection.", accentDots()),
      ]),
      section("Sound", [sr("Sound", "", sw("sound", "Sound"))]),
    ].join("");
    view("settings");
  };

  const about = () => {
    closeSheet();
    $("#setTitle").textContent = "About";
    $("#settingsBody").innerHTML = `<div class="set-group"><p class="pad">ChessSRS 0.2.0 is free software under GPL-3.0, a fork of Lichess Mobile. This demo runs entirely in your browser and saves nothing.</p><div class="lib-group"><a class="lib-row" href="https://github.com/cassandre60/ChessSRS" target="_blank" rel="noopener"><span>ChessSRS source</span></a><a class="lib-row" href="https://github.com/lichess-org/mobile" target="_blank" rel="noopener"><span>Lichess Mobile source</span></a></div></div>`;
    view("settings");
  };

  const importModal = () => {
    if (isrc !== "lichess") isrc = "file";
    closeSheet();
    $("#setTitle").textContent = "Import PGN";
    view("settings");
    $("#settingsBody").innerHTML = `<div class="set-group"><div class="seg wide">${[["lichess", "Lichess Study"], ["file", "PGN Text / File"]].map(([v, l]) => `<button data-a="isrc" data-v="${v}" aria-pressed="${v === isrc}">${l}</button>`).join("")}</div>
    <div id="i-file"${isrc === "file" ? "" : " hidden"}><textarea id="i-pgn" rows="6" spellcheck="false" aria-label="PGN text">${esc(SAMPLE)}</textarea><label class="filebtn">Choose a .pgn file<input type="file" id="i-f" accept=".pgn,.txt"></label></div>
    <div id="i-li"${isrc === "lichess" ? "" : " hidden"}><input id="i-url" placeholder="https://lichess.org/study/…" aria-label="Lichess study URL"></div>
    <input id="i-title" placeholder="Study Title (optional)" aria-label="Study title (optional)"><p class="err" id="i-err" role="alert" hidden></p>
    <button class="pill big" data-a="doimport">Import and Start Review</button></div>`;
  };

  function doImport() {
    const err = $("#i-err"), fail = m => { err.textContent = "Import failed: " + m; err.hidden = false; };
    if (isrc === "lichess") return fail("this demo can't reach Lichess. Paste PGN text instead.");
    try {
      const g = parsePGN($("#i-pgn").value), title = $("#i-title").value.trim() || g[0].title || "Imported Study";
      studies.push(mkStudy(title, g[0].side, g.map(x => ({ t: x.title, s: x.s }))));
      sel = studies.length - 1; practice = false; view("rev"); startSession();
    } catch (e) {
      fail(e.message);
    }
  }

  /* ---------- Action Handler Registry ---------- */
  const A = {
    close: closeSheet, picker, more, about, import: importModal, doimport: doImport, analyze, skip: pressS, cont,
    pick: el => { sel = +el.dataset.i; practice = false; closeSheet(); startSession(); },
    /* Tapping a square switches to that colour's scope as well as opening its drawer
       (`_openColourDrawer`). Tapping the colour already in scope only re-opens the drawer: the
       session underneath is already that colour's, so restarting it would throw away the queue. */
    square: el => { const v = el.dataset.v; if (sel !== v) { sel = v; practice = false; startSession(); } picker(v); },
    sacts: el => studyActions(+el.dataset.i),
    practice: () => { practice = !practice; closeSheet(); startSession(); },
    choose: () => picker(liveSide()),
    /* `createStudyInSide`: the same positions, freshly scheduled, under the same title in the other
       colour — deduplicated per side, so re-running it is a no-op rather than a second copy. And
       like the app it does not move the user: a study part-way through stays part-way through, so
       the session is left alone and only the chrome is refreshed. */
    create: () => {
      const s = tgt(), other = s.side === "w" ? "b" : "w";
      if (!studies.some(x => x.side === other && x.name === s.name)) {
        studies.push(mkStudy(s.name, other, s.lines.map(l => ({ t: l.t, s: l.s, note: l.note, noteSource: l.noteSource }))));
      }
      closeSheet(); head();
    },
    pause: () => { const s = tgt(); s.active = !s.active; closeSheet(); startSession(); },
    export: () => { closeSheet(); $("#setTitle").textContent = tgt().name; view("settings"); $("#settingsBody").innerHTML = `<div class="set-group"><pre id="x-pgn" style="white-space:pre-wrap;font:13px/1.7 var(--mono)">${esc(toPGN(tgt()))}</pre><div class="idle-actions"><button class="pill" data-a="copy">Copy PGN</button></div></div>`; },
    copy: el => {
      const txt = toPGN(tgt());
      (navigator.clipboard ? navigator.clipboard.writeText(txt) : Promise.reject()).then(
        () => el.textContent = "Copied",
        () => {
          const r = document.createRange(); r.selectNodeContents($("#x-pgn"));
          const s = getSelection(); s.removeAllRanges(); s.addRange(r);
          el.textContent = "Selected: press Ctrl+C";
        }
      );
    },
    rename: () => { closeSheet(); $("#setTitle").textContent = "Rename"; view("settings"); $("#settingsBody").innerHTML = `<div class="set-group"><input id="r-in" value="${esc(tgt().name)}" aria-label="Repertoire name" autofocus style="display:block;width:100%;margin-bottom:12px;background:transparent;border:1px solid var(--hair);border-radius:12px;padding:12px;color:var(--ink);font:14px var(--font-ui)"><div class="idle-actions"><button class="pill" data-a="dorename">Rename</button><button class="link" data-a="aback">Cancel</button></div></div>`; },
    dorename: () => { const v = $("#r-in").value.trim(); if (v) tgt().name = v; view("rev"); head(); },
    delete: () => { closeSheet(); $("#setTitle").textContent = "Delete"; view("settings"); $("#settingsBody").innerHTML = `<div class="set-group"><p class="pad">Delete ${esc(tgt().name)}? Its lines and review schedule are removed.</p><div class="idle-actions"><button class="link" data-a="aback">Cancel</button><button class="pill danger" data-a="dodelete">Delete</button></div></div>`; },
    dodelete: () => { const i = sa; studies.splice(i, 1); if (typeof sel === "number") sel = Math.min(sel, studies.length - 1); practice = false; view("rev"); startSession(); },
    /* Switching source rebuilds the form from state, as the app's dialog does — but the fields the
       user has already typed into are carried across, because losing a pasted PGN to a mis-tap
       on the tab would be the demo inventing a bug the app does not have. */
    isrc: el => {
      const keep = { pgn: $("#i-pgn").value, url: $("#i-url").value, title: $("#i-title").value };
      isrc = el.dataset.v;
      importModal();
      $("#i-pgn").value = keep.pgn; $("#i-url").value = keep.url; $("#i-title").value = keep.title;
    },
    ply: el => showPly(+el.dataset.i),
    aprev: () => showPly(an.i - 1),
    anext: () => showPly(an.i + 1),
    aback: () => { an = null; view("rev"); startSession(); },
    /* Library sheet's Settings row opens the full Settings view. */
    settings: settings,
    /* Settings handlers. SrsSettingsScreen is a ConsumerStatefulWidget: a tap writes to the
       preferences provider and the widget rebuilds from it. These do the same — write to `set`,
       re-apply the theme attributes, re-render the screen — rather than reaching into the DOM to
       flip aria-pressed on whichever node was clicked, which is both more markup to keep in sync
       and impossible to assert against outside a browser. */
    limit: el => { set.limit = +el.dataset.v; apply(); settings(); },
    retention: el => { set.retention = +el.dataset.v; apply(); settings(); },
    scheduler: el => { set.scheduler = el.dataset.v; apply(); settings(); },
    theme: el => { set.theme = el.dataset.v === "true"; apply(); settings(); },
    accent: el => { set.accent = el.dataset.v; apply(); settings(); },
    showHistory: () => { set.showHistory = !set.showHistory; apply(); settings(); },
    showArrows: () => { set.showArrows = !set.showArrows; apply(); settings(); },
    showNotes: () => { set.showNotes = !set.showNotes; apply(); settings(); },
    diagnostics: () => { set.diagnostics = !set.diagnostics; apply(); settings(); },
    sound: () => { set.sound = !set.sound; apply(); settings(); }
  };

  /* Theme and accent are applied the way the app applies them: as data attributes that the
     generated token file keys off. `sync-design.js` re-anchors the app's tokens from `:root` onto
     `.app` so the marketing page keeps its own palette, which means the attributes have to land on
     the demo root itself — on <html> they would never match `.app[data-theme=…]` and the app's
     light/dark and four-accent rules would silently never apply.

     The theme is normalised to the tokens' own vocabulary ("light" / "dark") here. The settings
     control carries booleans, and `data-theme="true"` matches neither block, which left the demo
     rendering in the light defaults no matter which control was tapped. */
  function apply() {
    host.dataset.theme = set.theme ? "dark" : "light";
    if (set.accent) host.dataset.accent = set.accent;
  }

  host.addEventListener("click", e => {
    if (e.target === $("#scrim")) return closeSheet();
    const a = e.target.closest("[data-a]");
    if (a && A[a.dataset.a]) A[a.dataset.a](a);
  });

  /* Reading a chosen .pgn into the textarea. Every other setting goes through the action
     registry; nothing carries a `data-k` any more, so the delegated input/change pair that used
     to funnel them is gone. */
  document.addEventListener("change", e => {
    if (e.target.id === "i-f" && e.target.files[0]) {
      e.target.files[0].text().then(t => $("#i-pgn").value = t);
    }
  });

  addEventListener("keydown", e => {
    const sheetOpen = $(".sheet.open");
    if (sheetOpen) {
      if (e.key === "Escape") closeSheet();
      else if (e.key === "Enter" && e.target.id === "r-in") A.dorename();
      return;
    }
    if (e.metaKey || e.ctrlKey || e.altKey || (document.activeElement !== document.body && !host.contains(document.activeElement)) || /INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)) return;
    if (an) {
      if (e.key === "ArrowLeft") showPly(an.i - 1);
      if (e.key === "ArrowRight") showPly(an.i + 1);
      return;
    }
    if (e.key.toLowerCase() === "s") pressS();
    else if (e.key === " " && (cur?.wait || host.contains(document.activeElement))) {
      // review_screen.dart wraps the whole screen in CallbackShortcuts, so Continue wins even when a
      // button holds focus. Swallowing the key is what stops Space from also counting as a click on
      // that button: a focused <button> activates on Space, which re-opened the scope drawer
      // immediately after Escape had closed it and made the session look frozen. The board used to
      // swallow it too — see the note in its keydown. Scoped to "focus is in the demo, or a verdict
      // is waiting" rather than to `cur` alone: with nothing focused the page still scrolls, which a
      // Flutter screen never has to care about.
      e.preventDefault();
      if (cur?.wait) cont();
    }
  });

  // Wire up sheet backdrop and Escape
  $("#scrim").addEventListener("click", closeSheet);
  // The search field filters the open drawer's studies; the query belongs to the field, not the
  // drawer, so re-rendering from it on every keystroke keeps both in agreement for free.
  $("#scopeSearch").addEventListener("input", () => picker(drawerSide));
  $("#moreBtn").addEventListener("click", more);
  $("#skipBtn").addEventListener("click", pressS);
  $("#contBtn").addEventListener("click", cont);
  $("#backBtn").addEventListener("click", () => { an = null; view("rev"); startSession(); });

  apply();
  startSession();
})();
