#!/usr/bin/env node
/**
 * scripts/sync-design.js
 *
 * Pulls the demo's design inputs out of the ChessSRS Flutter repository, so the web demo
 * tracks the app instead of a hand-copy of it.
 *
 * The app already exports its design system:
 *   design/tokens/tokens.css   CSS custom properties, verbatim from reference/styles.css
 *   design/tokens/tokens.json  the same tokens plus type scale, spacing and motion
 *   assets/fonts/*.ttf         Instrument Sans (UI) and Newsreader (study notes)
 *   assets/figurines/*.svg     K Q R B N notation figurines
 *   assets/pieces/<theme>/svg/*.svg  current piece geometry
 *
 * Everything this writes is generated. Nothing here invents a value: if the file it reads is
 * missing, it fails loudly rather than falling back to a guess, because a silent fallback is
 * exactly how a demo drifts away from the app while still looking plausible.
 *
 *   node scripts/sync-design.js            # verify + sync
 *   node scripts/sync-design.js --check    # fail if anything is stale (for CI)
 */
const fs = require('fs');
const path = require('path');

const APP_DIR =
  require('./resolve-app-dir').resolveAppDir() ||
  process.env.CHESSSRS_APP_DIR ||
  '/home/mohamed/Desktop/Github/Chess Repertoire SRS';
const SITE = path.resolve(__dirname, '..');
const CHECK = process.argv.includes('--check');

const BANNER = (src) =>
  `/* GENERATED by scripts/sync-design.js from ${src} in the ChessSRS app repo.\n` +
  `   Do not edit by hand — run \`node scripts/sync-design.js\`. */\n`;

const read = (rel) => fs.readFileSync(path.join(APP_DIR, rel), 'utf8');
const readBin = (rel) => fs.readFileSync(path.join(APP_DIR, rel));

/** Writes `content` only when it differs, and reports the outcome. */
function put(destRel, content) {
  const dest = path.join(SITE, destRel);
  const existed = fs.existsSync(dest);
  const same = existed && Buffer.isBuffer(content)
    ? fs.readFileSync(dest).equals(content)
    : existed && fs.readFileSync(dest, 'utf8') === content;
  if (same) { log(`  = ${destRel} (up to date)`); return 'same'; }
  if (CHECK) { dirty.push(destRel); return 'stale'; }
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, content);
  log(`  ${existed ? '~' : '+'} ${destRel}`);
  return existed ? 'updated' : 'created';
}

const log = (m) => process.stdout.write(m + '\n');
const dirty = [];

if (!fs.existsSync(APP_DIR)) {
  console.error(
    `[sync-design] App repo not found at ${APP_DIR}.\n` +
    `               Set CHESSSRS_APP_DIR to the ChessSRS checkout, or clone it alongside this repo.`
  );
  process.exit(1);
}

/* ------------------------------------------------------------------ tokens */

/**
 * The app's tokens.css is written for `:root`, because in the app it *is* the page. Here the
 * marketing site owns the page and keeps its own palette (warm cream, Instrument Serif), so
 * the app's tokens get re-anchored onto the demo container instead. Same values, different
 * scope — the demo then follows the app's colours without repainting the marketing page.
 */
function scopeTokens(css, scope) {
  return css
    .replace(/(^|\})\s*:root(?=[\s,{[])/g, `$1 ${scope}`)
    .replace(/:root\[data-theme=/g, `${scope}[data-theme=`)
    .replace(/:root\[data-accent=/g, `${scope}[data-accent=`)
    .replace(/:root:not\(/g, `${scope}:not(`)
    .replace(/:root/g, scope); // anything the patterns above missed
}

log('[sync-design] tokens');
const tokensSrc = 'design/tokens/tokens.css';
const scoped = scopeTokens(read(tokensSrc), '.app');

/* The app's reduced-motion block is written as a bare `:root{--dur:1ms}` plus a global
 * `*{...}` rule. The global half is fine to keep — honouring reduced motion site-wide is not
 * a fidelity question — but it is not scoped, so it stays unrewritten by design. */
put('assets/demo-tokens.css', BANNER(tokensSrc) + scoped);

/* ------------------------------------------------------------------ accents */

/* Hand-copying the accent list is how the previous sync drifted: it wrote the four accents
 * into the script itself. They come from tokens.json now. */
log('[sync-design] accents');
const metaSrc = 'design/tokens/tokens.json';
const tokens = JSON.parse(read(metaSrc));
const meta = {
  version: (read('pubspec.yaml').match(/^version:\s*([0-9.]+)/m) || [undefined, '0.0.0'])[1],
  fonts: { ui: tokens.font.ui.family, read: tokens.font.read.family },
  motion: tokens.motion || null,
  accents: tokens.color.accents,
  syncedAt: new Date().toISOString()
};
/* syncedAt would otherwise churn the file on every run and make `--check` useless. */
const metaStable = JSON.stringify({ ...meta, syncedAt: undefined }, null, 2).replace(
  /"syncedAt": null,?/,
  ''
);
/* Emitted as a script rather than fetched as JSON: the demo needs it synchronously, before it
   paints the first accent swatch, and a fetch would mean a flash of default styling. */
put(
  'assets/app-meta.js',
  `${BANNER(`pubspec.yaml + ${metaSrc}`)}window.CHESSSRS_META = ${metaStable.replace(/\n\s*}\n$/, '\n}')};\n`
);

/* ------------------------------------------------------------------ fonts */

/* The demo was rendering in the marketing site's Geist. The app specifies Instrument Sans for
 * UI and Newsreader for study notes, and the type scale in tokens.json is expressed in those
 * two families — so without these files the demo cannot be typographically faithful at all. */
log('[sync-design] fonts');
/* The app's font files are named for their variable axes, with literal brackets:
 * `InstrumentSans[wdth,wght].ttf`. Brackets in a URL are legal but need care in CSS url(),
 * in servers and in cache keys, so they are renamed on the way in. The bytes are untouched. */
for (const [src, dest] of [
  ['InstrumentSans[wdth,wght].ttf', 'InstrumentSans-var.ttf'],
  ['Newsreader[opsz,wght].ttf', 'Newsreader-var.ttf'],
]) {
  put(`assets/fonts/${dest}`, readBin(`assets/fonts/${src}`));
}

/* ------------------------------------------------------------------ figurines */

log('[sync-design] figurines');
/* Inlined rather than referenced, because a notation line can show a dozen of them and the
 * app's SrsSan swaps a leading piece letter for an SVG on every one. The markup is
 * `<svg viewBox=…><g fill="currentColor">`, so emitting the inner group keeps the colour under
 * CSS control exactly as the app's ColorFilter does. */
const figs = {};
for (const k of ['K', 'Q', 'R', 'B', 'N']) {
  const svg = read(`assets/figurines/${k}.svg`);
  const vb = viewBox(svg);
  const body = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!vb || !body) throw new Error(`could not parse figurine ${k}.svg`);
  figs[k] = { vb, body: body[1].replace(/\s+/g, ' ').trim() };
  put(`assets/figurines/${k}.svg`, svg);
}
put(
  'assets/figurines.js',
  `${BANNER('assets/figurines/*.svg')}window.FIGURINES = ${JSON.stringify(figs, null, 2)};\n`
);

/* ------------------------------------------------------------------ pieces */

/**
 * The app ships one SVG per piece per colour, with its colours baked in as literal fill and
 * stroke values. A demo needs to recolour pieces at runtime — light and dark themes, four
 * accents — so this extracts the geometry and re-emits it as bare shapes. The colour layers are
 * supplied by CSS instead, which is what the app's own `--wf/--ws/--wd` and `--bf/--bs/--bd`
 * tokens are for.
 *
 * Each piece file has four layers, and all four have to survive the trip:
 *
 *   <defs><g id="s">…</g></defs>      the silhouette — drawn three times as <use>
 *   …<g stroke-…><use/>×3</g>         halo (7), line (4.4), fill — the demo reuses the silhouette
 *   <g color=…>…</g>                  the detail strokes: a rook's crenellation bar, a knight's
 *                                    eye and mane, a king's base curve. Drawn with
 *                                    `stroke="currentColor"` so the app recolours them per piece.
 *
 * The detail group lives *after* `</defs>`, not inside it. Reading only `<defs>` silently dropped
 * it, which is what left the demo's pieces as flat silhouettes while the app's carry their detail.
 * Both are read by structure rather than by position, so a future regroup is picked up.
 */
log('[sync-design] pieces');
const PIECES = ['K', 'Q', 'R', 'B', 'N', 'P'];

/** The silhouette: the one <g id="…"> inside <defs>. */
function geometry(svg) {
  const defs = svg.match(/<defs>([\s\S]*?)<\/defs>/);
  if (!defs) throw new Error('no <defs> in piece svg');
  const g = defs[1].match(/<g id="[^"]+">([\s\S]*?)<\/g>/);
  if (!g) throw new Error('no <g id> in <defs>');
  return g[1].replace(/\s+/g, ' ').trim();
}

/**
 * The detail layer: the group after `</defs>` that sets `color` and paints with `currentColor`.
 * A pawn has none — its group is empty — so an empty string is a valid answer, not a failure.
 */
function detail(svg) {
  const tail = svg.split('</defs>')[1];
  if (!tail) throw new Error('piece svg has no content after </defs>');
  const groups = [...tail.matchAll(/<g\b([^>]*)>([\s\S]*?)<\/g>/g)];
  const g = groups.find(([, attrs]) => /\bcolor=/.test(attrs));
  if (!g) throw new Error('no <g color=…> detail layer after </defs>');
  return g[2].replace(/\s+/g, ' ').trim();
}

function viewBox(svg) {
  const m = svg.match(/viewBox="([^"]+)"/);
  return m ? m[1] : null;
}

let defs = '';
for (const p of PIECES) {
  const svg = read(`assets/pieces/light/svg/w${p}.svg`);
  const vb = viewBox(svg);
  if (!vb) throw new Error(`no viewBox on w${p}.svg`);
  // Both colours share one silhouette and one detail layer; the app's w*/b* files differ only in
  // their fills. Both are emitted as their own <g> so the demo can <use> them like the app does.
  defs += `\n  <g id="pc-${p}">${geometry(svg)}</g>`;
  const det = detail(svg);
  if (det) defs += `\n  <g id="pd-${p}">${det}</g>`;
}

const vbLight = viewBox(read('assets/pieces/light/svg/wP.svg'));
const pieces = `${BANNER('assets/pieces/<theme>/svg/*.svg')}window.PIECE_VIEWBOX = ${JSON.stringify(vbLight)};
window.PIECE_DEFS = \`${defs}\`;
`;
put('pieces.js', pieces);

/* ------------------------------------------------------------------ reference CSS */

/* The demo's visual layer is not hand-written. It is the app's own
   design/reference/styles.css, copied verbatim by scripts/sync-design.js so any
   upstream style change flows through on the next sync. The marketing-page
   chrome below is the only CSS this file keeps; the demo mounts inside the
   `.frame` / `.app` container that the reference CSS scopes everything to. */
log('[sync-design] reference css');
put('assets/demo-reference.css', BANNER('design/reference/styles.css') + read('design/reference/styles.css'));

/* ------------------------------------------------------------------ report */

if (CHECK && dirty.length) {
  console.error(
    `\n[sync-design] ${dirty.length} generated file(s) out of date:\n` +
    dirty.map((f) => `  - ${f}`).join('\n') +
    `\n\nRun \`node scripts/sync-design.js\` and commit the result.\n`
  );
  process.exit(1);
}

log('\n[sync-design] up to date.');